// ═══════════════════════════════════════════════════════════════════════════
// Objets passifs (PSV). Neuf familles primaires : projectile, element, familier,
// sante, ressource, exploration, economie, contrepartie, hybride.
// Pools : H héritage, B boss, S échoppe, P pacte, A sanctuaire, C cache,
// I chambre isolée, L bibliothèque, D épreuve, K coffre doré, M informateurs.
// Statut : « adaptation » (technique ou objet reconnaissable, règle inventée),
// « création originale », « canon adapté » (nom canonique, effet de jeu).
// ═══════════════════════════════════════════════════════════════════════════
(function () {
  const POOLS = { H: 'heritage', B: 'boss', S: 'boutique', P: 'pacte', A: 'sanctuaire', C: 'cache', I: 'isolee', L: 'bibliotheque', D: 'defi', K: 'coffre', M: 'machine' };
  const pools = t => { const o = {}; for (const m of t.split(' ').filter(Boolean)) { const k = POOLS[m[0]]; o[k] = +(m.slice(1) || 1); } return o; };
  const ic = (forme, a, b, c) => ({ forme, a, b, c });
  const O = (id, nom, famille, q, p, desc, effets, x = {}) => DON.objets.push(Object.assign({ id, nom, type: 'passif', famille, qualite: q, pools: pools(p), desc, effets, cumul: 'cumul', statut: 'création originale' }, x));
  const s = (st, a) => ({ s: st, a }), sp = (st, p) => ({ s: st, p }), sm = (st, m) => ({ s: st, m });

  // ── Modifications de projectile et formes de tir (24 comportements majeurs inclus) ──
  O('PSV_001', 'Empreinte du Rasengan', 'projectile', 3, 'H3 B1', 'Tir chargé : une sphère de chakra qui comprime sa cible.', [{ forme: 'orbe', charge: 0.6, mult: 3, portee: 5.5, vitesse: 8, perce: 2, element: 'futon' }], { statut: 'adaptation', icone: ic('sphere', '#6ab8f8', '#b0e0ff', '#ffffff'), visuel: { couche: 'bras', motif: 'lueur_poings', couleur: '#8ad0ff', prio: 4 }, ensemble: 'renard', tags: ['charge', 'futon'], cumul: 'unique' });
  O('PSV_002', 'Encre de dédoublement', 'projectile', 2, 'H3 S1', 'Chaque tir se dédouble, un peu moins fort.', [{ multi: 1, coefCadence: 0.9 }], { icone: ic('pinceau', '#2a2a3a', '#6a6a88', '#c8a060'), tags: ['multitir'] });
  O('PSV_003', 'Éventail de kunai', 'projectile', 2, 'H2 S1 K1', 'Trois kunai en éventail.', [{ multi: 2, coefCadence: 0.85 }], { icone: ic('kunai', '#d8dce8', '#8a90a0', '#8a2a2a'), tags: ['multitir'] });
  O('PSV_004', 'Parchemin des mille aiguilles', 'projectile', 3, 'H2 B1', 'Quatre senbon partent à chaque tir.', [{ multi: 3, coefCadence: 0.8 }, { apparence: 'senbon' }], { icone: ic('senbon', '#e8ecf4', '#8a90a0', '#c8a870'), tags: ['multitir'] });
  O('PSV_005', 'Kunai à marque de téléportation', 'projectile', 2, 'H2 L1', 'Les tirs suivent légèrement leur cible.', [{ traj: 'guidage', force: 1 }], { statut: 'adaptation', icone: ic('kunai', '#e0c050', '#a08020', '#2a2a2a'), tags: ['guidage'] });
  O('PSV_006', 'Insectes traqueurs', 'projectile', 3, 'H2 B1', 'Les tirs deviennent des insectes qui poursuivent les ennemis.', [{ traj: 'guidage', force: 2.5 }, { apparence: 'insecte' }, sp('degats', -10)], { statut: 'adaptation', ensemble: 'essaim', icone: ic('insecte', '#3a3a2a', '#6a6a4a', '#8a8a60'), visuel: { couche: 'aura', motif: 'insectes', prio: 3 }, tags: ['guidage'] });
  O('PSV_007', 'Fil de chakra', 'projectile', 1, 'H2 S1 K1', 'Les tirs ricochent sur les murs et les obstacles.', [{ traj: 'rebond' }], { icone: ic('chaine', '#a8c8f0', '#6a88b0', '#ffffff'), tags: ['ricochet'] });
  O('PSV_008', 'Senbon perforant', 'projectile', 2, 'H2 S1', 'Les tirs traversent les ennemis.', [{ traj: 'percant' }, s('vitesseTir', 1)], { icone: ic('senbon', '#f0f0f8', '#a0a0b0', '#6a2a2a'), tags: ['percement'] });
  O('PSV_009', 'Parchemin fantôme', 'projectile', 1, 'H2 L1', 'Les tirs passent au-dessus des obstacles.', [{ traj: 'spectral' }], { icone: ic('rouleau', '#c8d0e8', '#8890a8', '#6a6a88'), tags: ['spectral'] });
  O('PSV_010', 'Sable en orbite', 'projectile', 2, 'H2 L1', 'Les tirs tournent autour de vous avant de se disperser.', [{ traj: 'orbite' }, s('portee', 1)], { statut: 'adaptation', ensemble: 'sable', icone: ic('sable', '#d8b070', '#a8804a', '#f8e0a8'), visuel: { couche: 'aura', motif: 'sable_flottant', prio: 2 }, tags: ['orbite'] });
  O('PSV_011', 'Onde de la vague', 'projectile', 1, 'H2 S1', 'Les tirs ondulent : couverture plus large, précision moindre.', [{ traj: 'onde' }, s('degats', 0.3)], { icone: ic('goutte', '#4a8ae8', '#2a5aa8', '#c0e0ff'), tags: ['onde', 'suiton'] });
  O('PSV_012', 'Baika (expansion)', 'projectile', 3, 'H2 B1', 'Des tirs énormes et lents, deux fois plus forts.', [{ traj: 'lent' }, sm('degats', 2), { cadenceTir: 0.6 }, s('vitesseTir', -2)], { statut: 'adaptation', icone: ic('poing', '#e8a060', '#b8703a', '#c83a2a'), tags: ['orbe_lent'] });
  O('PSV_013', 'Fūma shuriken', 'projectile', 3, 'H2 B1', 'Lance un grand shuriken qui revient dans la main.', [{ forme: 'boomerang' }], { statut: 'adaptation', icone: ic('fuma', '#c8ccd8', '#6a7080', '#2a2a34'), tags: ['boomerang'], cumul: 'unique' });
  O('PSV_014', 'Canon de chakra', 'projectile', 4, 'P2 H1', 'Charge un rayon rougeoyant qui traverse tout.', [{ forme: 'rayon', charge: 1.0, duree: 0.33, coefTick: 0.9 }], { icone: ic('tete_renard', '#e05a2a', '#a03a1a', '#ffe060'), ensemble: 'renard', visuel: { couche: 'yeux', motif: 'yeux_rouges', couleur: '#ff4a2a', prio: 5 }, tags: ['rayon', 'charge'], cumul: 'unique' });
  O('PSV_015', 'Trait de chakra', 'projectile', 3, 'H2 B1', 'Chaque tir devient un trait instantané.', [{ forme: 'laser' }], { icone: ic('eclair', '#ff6a5a', '#c83a2a', '#ffe0d0'), tags: ['rayon'], cumul: 'unique' });
  O('PSV_016', 'Souffle continu', 'projectile', 3, 'H1 B1', 'Maintenir la visée émet un faisceau continu.', [{ forme: 'faisceau' }], { icone: ic('tornade', '#6ad0ff', '#3a90c8', '#e0f8ff'), tags: ['faisceau'], cumul: 'unique' });
  O('PSV_017', 'Empreinte du Kubikiribōchō', 'projectile', 3, 'H1 B1 P1', 'Un grand sabre balaie devant vous.', [{ forme: 'lame_longue' }, s('degats', 0.5)], { statut: 'adaptation', icone: ic('epee', '#c8ccd8', '#6a7080', '#5a4a3a'), visuel: { couche: 'dos', motif: 'cape', couleur: '#5a6a7a', prio: 2 }, tags: ['frappe_etendue'], cumul: 'unique' });
  O('PSV_018', 'Tantō de l’ANBU', 'projectile', 2, 'H2 S1', 'Frappe courte au sabre : puissante mais exposée.', [{ forme: 'lame' }], { statut: 'adaptation', icone: ic('lame', '#d0d8e8', '#7a8090', '#3a3040'), tags: ['frappe_courte'], cumul: 'unique' });
  O('PSV_019', 'Argile explosive C1', 'projectile', 3, 'P1 H1 B1', 'Lance des bombes d’argile ; attention au souffle.', [{ forme: 'bombe' }], { statut: 'adaptation', icone: ic('oiseau', '#f0e8d8', '#b8ac98', '#3a3a4a'), contrepartie: 'Les explosions peuvent vous blesser.', ensemble: 'argile', tags: ['bombe_lancee'], cumul: 'unique' });
  O('PSV_020', 'Chute céleste', 'projectile', 4, 'P2 B1', 'Visez un point : une météorite s’y écrase.', [{ forme: 'frappe', coef: 8 }], { statut: 'création originale d’après une technique célèbre (attribution à vérifier)', icone: ic('rocher', '#8a6a5a', '#5a4038', '#ff8a3a'), tags: ['frappe_differee'], cumul: 'unique' });
  O('PSV_021', 'Sphère téléguidée', 'projectile', 3, 'H1 B1 L1', 'Une seule sphère, guidée par la visée.', [{ forme: 'controle' }], { statut: 'adaptation', icone: ic('sphere', '#2a2a34', '#6a6a78', '#c0c0d0'), tags: ['emission_controlee'], cumul: 'unique' });
  O('PSV_022', 'Rotation céleste', 'projectile', 3, 'H1 A1', 'Tournoyer détruit les tirs proches et blesse autour.', [{ forme: 'rotation' }], { statut: 'adaptation (Hyūga)', icone: ic('tornade', '#e0e8ff', '#a0b0d8', '#ffffff'), ensemble: 'yeux', tags: ['attaque_circulaire'], cumul: 'unique' });
  O('PSV_023', 'Clone de relais', 'familier', 3, 'H2 B1', 'Un clone copie vos tirs (75 %).', [{ familier: 'FAM_RELAIS' }], { statut: 'adaptation', icone: ic('masque', '#f08a24', '#c8661a', '#28407c'), tags: ['tir_depuis_familier'] });
  O('PSV_024', 'Arsenal de Tenten (empreinte)', 'projectile', 2, 'H2 S1 L1', 'Chaque tir est suivi de deux autres (salve).', [{ salve: 2, coefCadence: 0.8 }], { statut: 'adaptation', icone: ic('rouleau', '#c83a2a', '#8a2a1a', '#e8d0a0'), tags: ['salve'] });
  O('PSV_025', 'Œil arrière', 'projectile', 1, 'H2 S1', 'Tire aussi vers l’arrière.', [{ arriere: 0.8 }], { icone: ic('oeil', '#e8e8f0', '#6a4a8a', '#1c1420'), ensemble: 'yeux', tags: ['tir_arriere'] });
  O('PSV_026', 'Croix de sceaux', 'projectile', 2, 'H2 L1', 'Parfois, tire dans les quatre directions (20 % + 5 % par chance, 60 % au plus).', [{ croix: 0.2 }], { icone: ic('sceau', '#c83a2a', '#e8c050', '#1c1420'), tags: ['croix'] });
  O('PSV_027', 'Parchemins-pièges', 'projectile', 2, 'H2 S1', 'Au bout de leur course, les tirs deviennent des mines.', [{ impact: 'mine' }], { icone: ic('tag', '#e8dcc0', '#c82a2a', '#6a5a4a'), tags: ['mine'] });
  O('PSV_028', 'Chidori nagashi (empreinte)', 'element', 3, 'H2 B1', 'La foudre saute de la cible à deux ennemis proches.', [{ impact: 'chaine', sauts: 2, r: 3, coef: 0.5 }, { element: 'raiton' }], { statut: 'adaptation', ensemble: 'tonnerre', icone: ic('eclair', '#a8d8ff', '#5a90d8', '#ffffff'), tags: ['chaine', 'raiton'] });
  O('PSV_029', 'Poing de Doton', 'projectile', 2, 'H2 S1', 'Chaque impact libère une petite onde de choc.', [{ impact: 'onde', r: 1.2, coef: 0.5 }, { element: 'doton' }], { icone: ic('rocher', '#9a7a5a', '#6a4a30', '#d8b890'), tags: ['onde', 'doton'] });
  O('PSV_030', 'Shuriken démultiplié', 'projectile', 2, 'H2 K1', 'Les tirs éclatent en quatre éclats à l’impact.', [{ impact: 'eclat', n: 4, coef: 0.35 }], { icone: ic('shuriken', '#c8ccd8', '#8a90a0', '#2a2a34'), tags: ['eclatement'] });
  O('PSV_031', 'Kunai du vent', 'projectile', 1, 'H2 S1', 'Les tirs accélèrent en vol.', [{ traj: 'acceleration' }, s('portee', 1)], { icone: ic('kunai', '#d0f0d8', '#7ab090', '#4a6a5a'), tags: ['futon'], ensemble: 'renard' });
  O('PSV_032', 'Poids de plomb', 'projectile', 1, 'H2 S1', 'Des tirs lourds qui repoussent fort.', [{ recul: 2 }, { taille: 1.2 }, s('vitesseTir', -1), s('degats', 0.5)], { icone: ic('poids', '#6a6a78', '#3a3a44', '#8a8a98'), ensemble: 'portes' });
  O('PSV_033', 'Senbon de précision', 'projectile', 1, 'H2 S2', 'Plus loin, plus vite.', [s('vitesseTir', 2), s('portee', 1.5), s('degats', 0.3)], { statut: 'adaptation', icone: ic('senbon', '#e8f0ff', '#8aa0c0', '#6a8ab0') });
  O('PSV_034', 'Kunai lestés', 'projectile', 2, 'H3 S1 K1', 'Des lames plus lourdes.', [s('degats', 1)], { icone: ic('kunai', '#a8acb8', '#5a5e6a', '#3a2a1a') });
  O('PSV_035', 'Sandales de course', 'projectile', 1, 'H2 S2', 'Vous vous déplacez plus vite.', [s('vitesse', 0.6)], { icone: ic('sandale', '#3a4a6a', '#e8e0d0', '#28407c'), visuel: { couche: 'corps', motif: 'bandeau_bras', couleur: '#28407c', prio: 1 } });
  O('PSV_036', 'Pilule du soldat (empreinte)', 'projectile', 2, 'H2 S1 B1', 'Cadence de tir augmentée.', [s('cadence', 0.5)], { statut: 'adaptation', icone: ic('pilule', '#f0e8a0', '#c8b050', '#ffffff') });
  O('PSV_037', 'Lunettes de visée', 'projectile', 1, 'H2 S2', 'Portée et vitesse des tirs accrues.', [s('portee', 2), s('vitesseTir', 1)], { icone: ic('masque', '#3a3a3a', '#1a1a1a', '#8a8a8a'), visuel: { couche: 'yeux', motif: 'masque', couleur: '#2a2a2a', prio: 1 } });
  O('PSV_038', 'Bandeau de Konoha', 'projectile', 2, 'H2 B2', 'Un peu de tout : dégâts, cadence, portée, vitesse, chance.', [s('degats', 0.3), s('cadence', 0.2), s('portee', 0.5), s('vitesse', 0.2), s('chance', 1)], { statut: 'canon adapté', icone: ic('bandeau', '#28407c', '#cfd2de', '#6a7088') });
  O('PSV_039', 'Masque de l’ANBU', 'projectile', 1, 'H2 S1 C1', 'Dégâts et chance.', [s('degats', 0.5), s('chance', 1)], { statut: 'adaptation', icone: ic('masque', '#e8e4dc', '#c83a2a', '#1c1420'), visuel: { couche: 'tete', motif: 'masque', couleur: '#e8e4dc', prio: 2 } });
  O('PSV_040', 'Gants de taijutsu', 'projectile', 2, 'H2 S1', 'Dégâts +0,7 ; les frappes de mêlée gagnent en portée.', [s('degats', 0.7), s('portee', 0.5)], { icone: ic('gant', '#3c9a3c', '#f28a22', '#2a782a'), ensemble: 'portes' });
  O('PSV_041', 'Cadence de la fleur de lotus', 'projectile', 2, 'H2 S1', 'Cadence très élevée, portée réduite.', [sm('cadence', 1.5), s('portee', -2)], { icone: ic('feuille', '#6ae07a', '#3a9a4a', '#e0ffe0'), contrepartie: 'Portée −2.', ensemble: 'portes', tags: ['anti-synergie'] });
  O('PSV_042', 'Pointe de précision', 'projectile', 2, 'H1 S1 L1', 'Les tirs grossissent : touchent mieux, plus lents.', [{ taille: 1.5 }, s('degats', 0.5), s('vitesseTir', -1.5)], { icone: ic('etoile', '#e0e0f0', '#a0a0c0', '#6060a0') });

  // ── Éléments et états ──
  O('PSV_043', 'Grande boule de feu (empreinte)', 'element', 2, 'H2 S1 B1', 'Tirs de feu : 25 % de brûlure (+5 % par chance, 70 % au plus).', [{ statut: 'brulure', chance: 0.25, chanceParChance: 0.05, max: 0.7 }, { element: 'katon' }, { apparence: 'sphere_feu' }], { statut: 'adaptation', icone: ic('flamme', '#c83018', '#f07820', '#ffe060'), tags: ['katon'] });
  O('PSV_044', 'Chakra de l’eau', 'element', 1, 'H2 S1', 'Tirs d’eau : ralentissent (30 %), laissent de petites flaques.', [{ statut: 'ralenti', chance: 0.3, duree: 2 }, { impact: 'flaque', coef: 0 }, { element: 'suiton' }], { icone: ic('goutte', '#4a8ae8', '#2a5aa8', '#c0e0ff'), tags: ['suiton'] });
  O('PSV_045', 'Courant foudroyant', 'element', 2, 'H2 S1', 'Tirs de foudre : 15 % d’immobiliser 0,3 s.', [{ statut: 'immobilise', chance: 0.15, chanceParChance: 0.03, max: 0.45, duree: 0.3 }, { element: 'raiton' }], { ensemble: 'tonnerre', icone: ic('eclair', '#f0f060', '#b0a020', '#ffffff'), tags: ['raiton'] });
  O('PSV_046', 'Lame de vent', 'element', 2, 'H2 S1', 'Tirs de vent : perçants, portée accrue.', [{ traj: 'percant' }, s('portee', 1.5), s('degats', 0.3), { element: 'futon' }], { ensemble: 'renard', icone: ic('tornade', '#c0f0d0', '#6ab080', '#ffffff'), tags: ['futon'] });
  O('PSV_047', 'Poing de terre', 'element', 1, 'H2 S1', 'Recul énorme, dégâts +0,7.', [{ recul: 2.5 }, s('degats', 0.7), s('vitesseTir', -0.8), { element: 'doton' }], { icone: ic('poing', '#9a7a5a', '#6a4a30', '#3a2a1a'), tags: ['doton'] });
  O('PSV_048', 'Poison de scorpion', 'element', 2, 'H2 S1 C1', '30 % d’empoisonner (+5 % par chance).', [{ statut: 'poison', chance: 0.3, chanceParChance: 0.05, max: 0.8 }], { icone: ic('fiole', '#6a3a8a', '#7ae04a', '#3a2a4a'), ensemble: 'marionnette' });
  O('PSV_049', 'Genjutsu du regard', 'element', 2, 'H2 L1', '15 % de plonger l’ennemi dans la confusion.', [{ statut: 'confus', chance: 0.15, chanceParChance: 0.04, max: 0.5, duree: 2 }], { ensemble: 'yeux', icone: ic('oeil', '#e8e8f0', '#c81e28', '#1c1420'), visuel: { couche: 'yeux', motif: 'yeux_rouges', couleur: '#e0202a', prio: 3 } });
  O('PSV_050', 'Glace éternelle', 'element', 3, 'H1 B1 L1', 'Gèle (15 %) ; un ennemi tué gelé éclate en six éclats.', [{ statut: 'gel', chance: 0.15, chanceParChance: 0.04, max: 0.5, duree: 1.5 }, { drapeau: 'eclatsGlace' }, { element: 'hyoton' }], { statut: 'adaptation', icone: ic('etoile', '#c0e8ff', '#80c0e8', '#ffffff') });
  O('PSV_051', 'Ombre liante', 'element', 2, 'H2 L1', '12 % d’immobiliser 1,2 s (+3 % par chance).', [{ statut: 'immobilise', chance: 0.12, chanceParChance: 0.03, max: 0.45, duree: 1.2 }], { statut: 'adaptation', icone: ic('racine', '#2a2238', '#1c1428', '#6a5a80') });
  O('PSV_052', 'Encre des bêtes', 'element', 2, 'H2 L1', 'Tirs d’encre : 12 % de charmer 3 s.', [{ statut: 'charme', chance: 0.12, chanceParChance: 0.03, max: 0.4, duree: 3 }, { apparence: 'encre' }], { statut: 'adaptation', icone: ic('pinceau', '#1a1a2a', '#4a4a6a', '#e8e0d0') });
  O('PSV_053', 'Flammes noires', 'element', 4, 'P2', 'Les brûlures durent trois fois plus et font 50 % de plus ; 20 % de brûler.', [{ drapeau: 'flammesNoires' }, { statut: 'brulure', chance: 0.2, chanceParChance: 0.04, max: 0.6 }, { element: 'katon' }], { statut: 'adaptation (attribution à vérifier)', ensemble: 'yeux', icone: ic('flamme', '#1a0a1a', '#5a2a6a', '#b060ff'), visuel: { couche: 'aura', couleur: '#3a1a4a', prio: 4 } });
  O('PSV_054', 'Marque de Jashin', 'contrepartie', 2, 'P2', 'Quand vous êtes blessé, tous les ennemis subissent 15 dégâts.', [{ quand: 'degat_recu', faire: { type: 'degats_tous', degats: 15, couleur: '#a01020' } }], { statut: 'adaptation', ensemble: 'interdit', icone: ic('sceau', '#a01020', '#1c1420', '#e0d0d0'), visuel: { couche: 'peau', motif: 'marque', couleur: '#a01020', prio: 3 } });
  O('PSV_055', 'Chakra du renard', 'element', 3, 'H1 B2 P1', 'Dégâts +1, vitesse +0,2 ; une queue de chakra apparaît.', [s('degats', 1), s('vitesse', 0.2)], { statut: 'adaptation', ensemble: 'renard', icone: ic('tete_renard', '#f08a24', '#c8661a', '#ffe060'), visuel: { couche: 'aura', motif: 'queues', n: 1, couleur: '#f0a030', prio: 3 } });
  O('PSV_056', 'Bulle de chakra rouge', 'element', 3, 'H1 B1 P1', 'Blessé, vous libérez huit tirs de chakra.', [{ quand: 'degat_recu', faire: { type: 'projectiles_cercle', n: 8, coef: 1.2 } }, s('degats', 0.5)], { ensemble: 'renard', icone: ic('sphere', '#e04a2a', '#a02a1a', '#ffc080') });
  O('PSV_057', 'Crapaud d’huile', 'element', 2, 'H1 L1 A1', 'Les tirs laissent parfois de l’huile qui s’embrase au feu.', [{ impact: 'flaque', coef: 0 }, s('degats', 0.4)], { ensemble: 'ermite', icone: ic('crapaud', '#8a6a3a', '#d8c890', '#1c1420') });
  O('PSV_058', 'Armure de foudre', 'element', 3, 'H1 B1', 'Vitesse +0,5, cadence +0,3.', [s('vitesse', 0.5), s('cadence', 0.3)], { statut: 'adaptation', ensemble: 'tonnerre', icone: ic('eclair', '#e0f0ff', '#8ab0e0', '#ffffff'), visuel: { couche: 'aura', couleur: '#a0d0ff', prio: 3 } });
  O('PSV_059', 'Racines du bois', 'element', 3, 'H1 B1 A1', 'Les tirs font parfois jaillir des racines qui immobilisent (15 %).', [{ statut: 'immobilise', chance: 0.15, chanceParChance: 0.03, max: 0.5, duree: 1.5 }, s('degats', 0.5)], { statut: 'adaptation (Mokuton)', icone: ic('racine', '#6a4a2a', '#4a3018', '#8ac060') });
  O('PSV_060', 'Os de l’ossature', 'element', 3, 'H1 B1 P1', 'Tirs d’os : perçants, un ricochet.', [{ traj: 'percant' }, { traj: 'rebond' }, { apparence: 'os' }, s('degats', 0.3)], { statut: 'adaptation', ensemble: 'experimental', icone: ic('os', '#ece4d0', '#b8ac98', '#6a5a4a') });

  // ── Familiers et orbitaux ──
  O('PSV_061', 'Clone de l’ombre', 'familier', 2, 'H2 S1', 'Un clone vous suit et tire des kunai.', [{ familier: 'FAM_CLONE' }], { statut: 'adaptation', icone: ic('masque', '#f6cf3e', '#c99a26', '#28407c'), ensemble: 'meute' });
  O('PSV_062', 'Gamakichi', 'familier', 2, 'H2 A1', 'Un petit crapaud qui crache des bulles ralentissantes.', [{ familier: 'FAM_GAMAKICHI' }], { statut: 'canon adapté', ensemble: 'meute', icone: ic('crapaud', '#d86a2a', '#f0b070', '#3a1a10') });
  O('PSV_063', 'Katsuyu miniature', 'familier', 2, 'H2 A2', 'Toutes les 5 salles nettoyées, une limace apporte un cœur.', [{ familier: 'FAM_KATSUYU' }], { statut: 'canon adapté', ensemble: 'meute', icone: ic('limace', '#e8e8f0', '#6a8ae8', '#1c1420') });
  O('PSV_064', 'Serpent des manches', 'familier', 2, 'H1 P1', 'Un serpent tourne autour de vous et mord.', [{ familier: 'FAM_SERPENT' }], { statut: 'adaptation', ensemble: 'experimental', icone: ic('serpent', '#7a9a4a', '#d8d8a0', '#c83a2a') });
  O('PSV_065', 'Sable protecteur', 'familier', 2, 'H2 B1', 'Deux orbitaux de sable bloquent les tirs ennemis.', [{ familier: 'FAM_SABLE' }, { familier: 'FAM_SABLE' }], { statut: 'adaptation', ensemble: 'sable', icone: ic('sable', '#d8b070', '#a8804a', '#f8e0a8') });
  O('PSV_066', 'Kunai tournoyants', 'familier', 1, 'H2 S1', 'Trois kunai tournent autour de vous (ne bloquent pas).', [{ familier: 'FAM_KUNAI_ORB' }, { familier: 'FAM_KUNAI_ORB' }, { familier: 'FAM_KUNAI_ORB' }], { icone: ic('kunai', '#d8dce8', '#8a90a0', '#c83a2a') });
  O('PSV_067', 'Corbeau messager', 'familier', 2, 'H1 L1 P1', 'Un corbeau aveugle les ennemis (confusion).', [{ familier: 'FAM_CORBEAU' }], { statut: 'adaptation', ensemble: 'yeux', icone: ic('corbeau', '#1c1420', '#2a2a3a', '#d0a040') });
  O('PSV_068', 'Pakkun', 'familier', 1, 'H2 S1 L1', 'Un chien ninja flaire les murs secrets.', [{ familier: 'FAM_PAKKUN' }], { statut: 'canon adapté', ensemble: 'meute', icone: ic('chien', '#c8a870', '#8a6a4a', '#1c1420') });
  O('PSV_069', 'Petit chien de chasse', 'familier', 2, 'H2 S1', 'Un chien fonce dans la direction de tir.', [{ familier: 'FAM_AKAMARU' }], { ensemble: 'meute', icone: ic('chien', '#f0ece4', '#c8c0b0', '#1c1420') });
  O('PSV_070', 'Kikaichū', 'familier', 2, 'H2 L1', 'Un essaim ramasse les pièces et pique les ennemis.', [{ familier: 'FAM_INSECTES' }], { statut: 'canon adapté', ensemble: 'essaim', icone: ic('insecte', '#2a2a2a', '#5a5a4a', '#8a8a60') });
  O('PSV_071', 'Oiseau d’argile', 'familier', 3, 'H1 B1 P1', 'Plonge sur un ennemi et explose toutes les 4 s.', [{ familier: 'FAM_OISEAU_ARGILE' }], { statut: 'adaptation', ensemble: 'argile', icone: ic('oiseau', '#f0e8d8', '#b8ac98', '#3a3a4a') });
  O('PSV_072', 'Karasu', 'familier', 2, 'H1 B1', 'Une marionnette attaque au plus près.', [{ familier: 'FAM_KARASU_ATT' }], { statut: 'canon adapté', ensemble: 'marionnette', icone: ic('marionnette', '#6a5a4a', '#c83a4a', '#3a3040') });
  O('PSV_073', 'Kuroari', 'familier', 2, 'H1 L1', 'Une marionnette-piège capture un ennemi toutes les 8 s.', [{ familier: 'FAM_KUROARI' }], { statut: 'canon adapté', ensemble: 'marionnette', icone: ic('marionnette', '#2a2a30', '#6a6a78', '#1c1420') });
  O('PSV_074', 'Sanshōuo', 'familier', 2, 'H1 A1', 'Une marionnette-bouclier bloque les tirs devant vous.', [{ familier: 'FAM_SANSHOUO' }], { statut: 'canon adapté', ensemble: 'marionnette', icone: ic('bouclier', '#6a6a78', '#a8a8b8', '#3a3a44') });
  O('PSV_075', 'Papillons de papier', 'familier', 2, 'H1 A1', 'Quatre papillons tournent, bloquent et coupent.', [{ familier: 'FAM_PAPIER' }, { familier: 'FAM_PAPIER' }, { familier: 'FAM_PAPIER' }, { familier: 'FAM_PAPIER' }], { statut: 'adaptation', ensemble: 'papier', icone: ic('papier', '#f4f0e8', '#c8c0b0', '#a8a090') });
  O('PSV_076', 'Tigres d’encre', 'familier', 2, 'H1 L1', 'Deux fauves d’encre chassent vos ennemis.', [{ familier: 'FAM_TIGRE_ENCRE' }, { familier: 'FAM_TIGRE_ENCRE' }], { statut: 'adaptation', ensemble: 'meute', icone: ic('pinceau', '#1a1a2a', '#6a6a88', '#e8e0d0') });
  O('PSV_077', 'Clone de sable', 'familier', 3, 'H1 B1', 'Un clone de sable copie vos tirs (60 %).', [{ familier: 'FAM_CLONE_SABLE' }], { ensemble: 'sable', icone: ic('sable', '#c8a060', '#8a6a3a', '#f0d8a0') });
  O('PSV_078', 'Serpent blanc', 'familier', 1, 'H2 P1', 'Un serpent albinos mord l’ennemi le plus proche.', [{ familier: 'FAM_SERPENT_BLANC' }], { ensemble: 'experimental', icone: ic('serpent', '#e8e4d0', '#b8b4a0', '#c83a2a') });
  O('PSV_079', 'Luciole des ermites', 'familier', 1, 'H1 A2', 'Une luciole éclaire la pénombre ; chance +1.', [{ familier: 'FAM_LUCIOLE' }, s('chance', 1)], { ensemble: 'ermite', icone: ic('etoile', '#f0f060', '#b0b020', '#ffffff') });
  O('PSV_080', 'Poupée d’entraînement', 'familier', 1, 'H1 S1', 'Une poupée attire l’attention des ennemis.', [{ familier: 'FAM_POUPEE' }], { icone: ic('marionnette', '#c8a060', '#b83a2a', '#9a7840') });
  O('PSV_081', 'Miroirs de glace', 'familier', 3, 'H1 B1', 'Deux miroirs orbitaux renvoient les tirs ennemis.', [{ familier: 'FAM_MIROIR' }, { familier: 'FAM_MIROIR' }], { statut: 'adaptation', icone: ic('bouclier', '#c0e8ff', '#80c0e8', '#ffffff') });
  O('PSV_082', 'Crapaud messager', 'familier', 1, 'H1 A1 L1', 'Toutes les 6 salles nettoyées, un crapaud rapporte une clé.', [{ familier: 'FAM_CRAPAUD_CLE' }], { ensemble: 'ermite', icone: ic('crapaud', '#6a8a3a', '#e8c050', '#1c1420') });

  // ── Santé et protection ──
  O('PSV_083', 'Bol de ramen d’Ichiraku', 'sante', 1, 'H1 B2 S1', 'Un contenant de vitalité et un soin complet.', [{ sante: { cont: 1, soinTotal: true } }], { statut: 'canon adapté', icone: ic('bol', '#c8a060', '#f0d8a0', '#e8e0d0'), cumul: 'cumul' });
  O('PSV_084', 'Onigiri', 'sante', 0, 'H1 S2 B1', 'Un contenant de vitalité.', [{ sante: { cont: 1 } }], { icone: ic('onigiri', '#f0f0f0', '#d0d0d0', '#1c2a1c') });
  O('PSV_085', 'Dango', 'sante', 1, 'H1 S2', 'Un contenant de vitalité et un cœur de soin.', [{ sante: { cont: 1, soin: 2 } }], { icone: ic('dango', '#f0a0b8', '#f0f0e0', '#8ad08a') });
  O('PSV_086', 'Pilule écarlate', 'sante', 2, 'H1 P1 B1', 'Dégâts +1 et un contenant, mais un peu plus lent.', [s('degats', 1), { sante: { cont: 1 } }, s('vitesse', -0.2)], { statut: 'création originale', icone: ic('pilule', '#d83a3a', '#8a1a1a', '#ffffff'), contrepartie: 'Vitesse −0,2.' });
  O('PSV_087', 'Sceau de régénération', 'sante', 3, 'A2 B1', 'Toutes les 3 salles nettoyées, soigne une demi-unité.', [{ quand: 'salle_nettoyee', tousLes: 3, faire: { type: 'soin', demis: 1 } }], { statut: 'adaptation (Byakugō, attribution à vérifier)', icone: ic('sceau', '#a050d0', '#e8d060', '#ffffff'), visuel: { couche: 'peau', motif: 'point_front', couleur: '#a050d0', prio: 2 } });
  O('PSV_088', 'Cape de chakra protecteur', 'sante', 1, 'A2 S1 H1', 'Deux réserves de chakra protecteur.', [{ sante: { prot: 4 } }], { icone: ic('bouclier', '#4a8ae8', '#c0e0ff', '#2a4a9a'), visuel: { couche: 'dos', motif: 'cape', couleur: '#3a6ac8', prio: 1 } });
  O('PSV_089', 'Cœur volé', 'sante', 3, 'P1 I1 B1', 'À votre mort, vous vous relevez avec un contenant (l’objet est consommé).', [], { statut: 'adaptation', icone: ic('coeur', '#6a1a2a', '#3a0a14', '#c83a4a'), cumul: 'cumul' });
  O('PSV_090', 'Ossature renforcée', 'sante', 2, 'H1 P1', 'Deux enveloppes osseuses.', [{ sante: { os: 2 } }], { statut: 'adaptation', ensemble: 'experimental', icone: ic('os', '#e8e0cc', '#a89c84', '#6a5a4a') });
  O('PSV_091', 'Sceau maudit', 'contrepartie', 3, 'P3', 'Deux réserves instables, dégâts +0,5 ; les pactes deviennent plus fréquents (+20 %).', [{ sante: { instable: 4 } }, s('degats', 0.5)], { statut: 'adaptation', ensemble: 'interdit', icone: ic('sceau', '#1c1420', '#a01020', '#6a2a8a'), visuel: { couche: 'peau', motif: 'marque', couleur: '#1c1420', prio: 4 } });
  O('PSV_092', 'Porte de la Vie', 'contrepartie', 3, 'P1 B1 D1', 'Dégâts +1,5, cadence +0,4, mais un contenant en moins.', [s('degats', 1.5), s('cadence', 0.4), { sante: { retraitCont: 1 } }], { statut: 'adaptation (Huit Portes)', ensemble: 'portes', icone: ic('poing', '#6ae07a', '#3a9a4a', '#ffffff'), contrepartie: '−1 contenant de vitalité.', visuel: { couche: 'aura', couleur: '#8af07a', prio: 3 } });
  O('PSV_093', 'Chakra de la limace', 'sante', 2, 'A2 H1', 'Les cœurs soignent deux fois plus.', [{ drapeau: 'soinsDoubles' }], { ensemble: 'ermite', icone: ic('limace', '#c0d8f0', '#6a8ae8', '#1c1420') });
  O('PSV_094', 'Trousse de terrain', 'sante', 1, 'H2 S1', 'Un contenant ; les cœurs lâchés sont parfois doublés.', [{ sante: { cont: 1 } }, { quand: 'salle_nettoyee', chance: 0.12, faire: { type: 'ramassable', ramassable: 'coeur' } }], { icone: ic('coffre', '#e8e0d0', '#c83a2a', '#ffffff') });
  O('PSV_095', 'Sceau vital de la famille', 'sante', 2, 'A1 H1', 'Un sceau vital partiel, puis un nouveau à chaque étage.', [{ sante: { partiel: 1 } }, { quand: 'etage', faire: { type: 'ramassable', ramassable: 'partiel' } }], { icone: ic('coeur', '#f0ecdc', '#c8a040', '#ffffff') });
  O('PSV_096', 'Substitution instinctive', 'sante', 3, 'H1 A1', '15 % + 3 % par chance d’esquiver un coup par une bûche (50 % au plus).', [{ drapeau: 'substitution' }], { statut: 'adaptation (Kawarimi)', icone: ic('rouleau', '#8a5a30', '#c89a60', '#3a2a1a') });
  O('PSV_097', 'Armure de sable absolue', 'sante', 4, 'B1 A1', 'Les coups d’un cœur entier ne retirent qu’une demi-unité.', [{ drapeau: 'armureSable' }, s('vitesse', -0.3)], { statut: 'adaptation', ensemble: 'sable', icone: ic('bouclier', '#d8b070', '#a8804a', '#f8e0a8'), contrepartie: 'Vitesse −0,3.', visuel: { couche: 'peau', motif: 'marque', couleur: '#c8a060', prio: 2 } });
  O('PSV_098', 'Chakra du démon scellé', 'contrepartie', 3, 'P2', 'Trois réserves instables, mais un contenant en moins.', [{ sante: { instable: 6, retraitCont: 1 } }], { ensemble: 'interdit', icone: ic('coeur', '#5a2a7a', '#2a1040', '#e060ff'), contrepartie: '−1 contenant.' });

  // ── Explosifs, clés et ressources ──
  O('PSV_099', 'Sac de parchemins', 'ressource', 1, 'H1 S2 K1', 'Cinq parchemins explosifs.', [{ res: { explosifs: 5 } }], { icone: ic('tag', '#e8dcc0', '#c82a2a', '#6a5a4a') });
  O('PSV_100', 'Parchemins à fragmentation', 'ressource', 2, 'H1 S1', 'Vos explosions projettent quatre kunai.', [{ drapeau: 'explosifsCroix' }, { res: { explosifs: 2 } }], { icone: ic('tag', '#e8dcc0', '#3a3a44', '#6a5a4a') });
  O('PSV_101', 'Mèche longue', 'ressource', 1, 'S2 H1', 'Explosions plus larges, mèche plus longue.', [{ drapeau: 'mecheLongue' }, { drapeau: 'grandeExplosion' }, { res: { explosifs: 1 } }], { icone: ic('tag', '#e8dcc0', '#f0a030', '#6a5a4a'), contrepartie: 'Délai +0,5 s.' });
  O('PSV_102', 'Parchemins incendiaires', 'ressource', 2, 'H1 S1', 'Vos explosions laissent des flammes (alliées).', [{ drapeau: 'explosifsFeu' }, { res: { explosifs: 2 } }, { element: 'katon' }], { icone: ic('tag', '#e8dcc0', '#f07820', '#c83018') });
  O('PSV_103', 'Parchemins chercheurs', 'ressource', 2, 'H1 S1', 'Vos explosifs posés glissent vers les ennemis.', [{ drapeau: 'explosifsGuides' }, { res: { explosifs: 2 } }], { icone: ic('tag', '#e8dcc0', '#3a6ad8', '#6a5a4a') });
  O('PSV_104', 'Grand parchemin', 'ressource', 2, 'H1 S1 K1', 'Explosions 50 % plus larges, +10 dégâts.', [{ drapeau: 'grandeExplosion' }, { res: { explosifs: 1 } }], { icone: ic('rouleau', '#e8dcc0', '#c82a2a', '#8a6a3a') });
  O('PSV_105', 'Trousseau du geôlier', 'ressource', 1, 'H1 S1 K1', 'Trois clés de sceau.', [{ res: { cles: 3 } }], { icone: ic('cle', '#e8c050', '#a08020', '#f0e8d0') });
  O('PSV_106', 'Épingle de crochetage', 'ressource', 3, 'C1 K1 S1', 'Portes et coffres verrouillés s’ouvrent sans clé.', [{ drapeau: 'crochetage' }], { icone: ic('cle', '#c8ccd8', '#6a7080', '#3a3a44') });
  O('PSV_107', 'Bourse-grenouille', 'ressource', 1, 'H1 S1 M1', '+10 Ryō ; 20 % des Ryō ramassés comptent double.', [{ res: { ryo: 10 } }], { statut: 'canon adapté', icone: ic('bourse', '#6a9a3a', '#e8c050', '#1c1420') });
  O('PSV_108', 'Aimant de chakra', 'ressource', 1, 'S2 H1', 'Attire Ryō, clés, explosifs et cœurs.', [{ drapeau: 'aimant' }], { icone: ic('anneau', '#c83a3a', '#5a5a64', '#ffffff') });
  O('PSV_109', 'Parchemin d’invocation vide', 'ressource', 1, 'H1 L1', 'Un rouleau tactique à chaque nouvel étage.', [{ quand: 'etage', faire: { type: 'ramassable', ramassable: 'rouleau' } }], { icone: ic('rouleau', '#ece0c4', '#a87c48', '#e8c050') });
  O('PSV_110', 'Argile infinie', 'ressource', 3, 'P1 B1 C1', 'Dix explosifs ; vos explosions ne vous blessent plus.', [{ res: { explosifs: 10 } }, { drapeau: 'immuniteExplosion' }], { ensemble: 'argile', icone: ic('oiseau', '#f0e8d8', '#b8ac98', '#e8c050') });

  // ── Exploration et salles ──
  O('PSV_111', 'Carte du labyrinthe', 'exploration', 1, 'S2 H1 L1', 'Révèle le plan de chaque étage (hors secrets).', [{ drapeau: 'plan' }], { icone: ic('carte', '#e8dcc0', '#8a6a3a', '#c83a2a') });
  O('PSV_112', 'Boussole du sceau', 'exploration', 1, 'S2 H1 L1', 'Révèle l’emplacement des salles spéciales.', [{ drapeau: 'boussole' }], { icone: ic('boussole', '#c8a050', '#e8e0d0', '#c83a2a') });
  O('PSV_113', 'Byakugan (empreinte)', 'exploration', 2, 'H1 L1 C1', 'Voit tout l’étage, secrets compris.', [{ drapeau: 'byakugan' }, s('portee', 0.5)], { statut: 'adaptation', ensemble: 'yeux', icone: ic('oeil', '#f0f0f8', '#c9c2e6', '#ffffff'), visuel: { couche: 'yeux', motif: 'yeux_rouges', couleur: '#e0dcf8', prio: 2 } });
  O('PSV_114', 'Rouleau des voies secrètes', 'exploration', 2, 'L2 C1', 'Les murs secrets montrent une fissure.', [{ drapeau: 'indicesSecrets' }], { icone: ic('rouleau', '#c8c0a0', '#6a5a3a', '#3a3030') });
  O('PSV_115', 'Lévitation de chakra', 'exploration', 3, 'A2 B1', 'Vous survolez fosses et pièges au sol.', [{ vol: true }], { icone: ic('plume', '#e0e8ff', '#a0b0d8', '#6a7aa8'), visuel: { couche: 'dos', motif: 'plumes', couleur: '#e0e8ff', prio: 3 } });
  O('PSV_116', 'Ailes de papier', 'exploration', 3, 'A1 P1 B1', 'Des ailes de papier : lévitation.', [{ vol: true }, s('portee', -0.5)], { statut: 'adaptation', ensemble: 'papier', icone: ic('papier', '#f4f0e8', '#c8c0b0', '#8a8070'), visuel: { couche: 'dos', motif: 'plumes', couleur: '#f4f0e8', prio: 4 } });
  O('PSV_117', 'Détecteur de pièges', 'exploration', 1, 'S2 H1', 'Immunité aux pics, flaques et sables mouvants.', [{ drapeau: 'immuniteSol' }], { icone: ic('sandale', '#6a6a78', '#c8c8d8', '#3a3a44') });
  O('PSV_118', 'Grelot de l’examen', 'exploration', 1, 'H1 D2', 'Les salles d’épreuve révèlent leur récompense ; chance +1.', [s('chance', 1)], { icone: ic('cloche', '#e8c050', '#a08020', '#c83a2a') });
  O('PSV_119', 'Sac à double fond', 'exploration', 2, 'S1 H1', 'Deux poches pour les consommables.', [{ drapeau: 'pocheDouble' }], { icone: ic('bourse', '#8a6a4a', '#5a4630', '#e8c050') });
  O('PSV_120', 'Collier à deux charmes', 'exploration', 2, 'S1 C1', 'Deux emplacements de talisman.', [{ drapeau: 'talismanDouble' }], { icone: ic('anneau', '#e8c050', '#a08020', '#c83a4a') });

  // ── Économie, pools et relances ──
  O('PSV_121', 'Carte de membre de l’échoppe', 'economie', 3, 'S1 I1', 'Tous les prix de l’échoppe sont divisés par deux.', [{ drapeau: 'soldes' }], { icone: ic('carte', '#e8c050', '#a08020', '#1c1420') });
  O('PSV_122', 'Coupon du marchand', 'economie', 2, 'S1 M1', 'Le premier achat de chaque étage est gratuit.', [{ drapeau: 'coupon' }], { icone: ic('tag', '#f0e8a0', '#c8b050', '#6a5a2a') });
  O('PSV_123', 'Livret d’épargne', 'economie', 1, 'S1 M1', 'À chaque étage, +10 % de vos Ryō (10 au plus).', [{ quand: 'etage', faire: { type: 'interets' } }], { icone: ic('livre', '#6a9a3a', '#e8c050', '#1c1420') });
  O('PSV_124', 'Réputation de client', 'economie', 2, 'S1', 'Un étal d’objet supplémentaire dans chaque échoppe.', [], { icone: ic('pieces', '#f0c030', '#c8d0dc', '#b08010') });
  O('PSV_125', 'Dés de la grande perdante', 'economie', 1, 'M2 S1', 'Chance −1, mais les machines de loterie paient double.', [s('chance', -1), { drapeau: 'loterieDouble' }], { statut: 'adaptation (surnom canonique)', icone: ic('etoile', '#e8e0d0', '#c83a2a', '#1c1420'), contrepartie: 'Chance −1.' });
  O('PSV_126', 'Livre de l’ermite', 'economie', 3, 'L2 A1', 'Les salles d’héritage proposent un second objet (choix).', [], { icone: ic('livre', '#c83a2a', '#6a9a3a', '#e8e0d0') });
  O('PSV_127', 'Sceau de réécriture', 'economie', 2, 'L1 S1', 'Une relance ne peut plus donner un objet de qualité inférieure.', [], { icone: ic('sceau', '#3a3040', '#e8dcc0', '#c83a2a') });
  O('PSV_128', 'Tampon du marchand', 'economie', 1, 'S1 M1', 'Ramasser des Ryō donne parfois un rouleau (5 %).', [{ quand: 'ryo_ramasse', chance: 0.05, faire: { type: 'ramassable', ramassable: 'rouleau' } }], { icone: ic('tag', '#c83a2a', '#e8dcc0', '#3a2a1a') });
  O('PSV_129', 'Contrat de Kakuzu', 'economie', 2, 'P1 M1', 'Les pactes se paient en Ryō (20 par contenant) si vous les avez.', [{ drapeau: 'pacteRyoOption' }], { statut: 'adaptation', ensemble: 'interdit', icone: ic('bourse', '#2a3a2a', '#e8c050', '#c83a2a') });
  O('PSV_130', 'Bourse de l’organisation', 'economie', 1, 'P1 S1', '+15 Ryō.', [{ res: { ryo: 15 } }], { icone: ic('bourse', '#1e1e28', '#c8303a', '#f0ece4') });

  // ── Contreparties, déclencheurs et résonances ──
  O('PSV_131', 'Sceau de la mort (empreinte)', 'contrepartie', 4, 'P1', 'Dégâts ×2, mais deux contenants en moins.', [sm('degats', 2), { sante: { retraitCont: 2 } }], { statut: 'adaptation (attribution à vérifier)', ensemble: 'interdit', icone: ic('crane', '#e8e4d0', '#1c1420', '#a01020'), contrepartie: '−2 contenants.', visuel: { couche: 'aura', couleur: '#e8e4d0', prio: 4 } });
  O('PSV_132', 'Rage du réceptacle', 'contrepartie', 2, 'H1 P1', 'Chaque blessure : +0,8 dégâts pour la salle (3 fois au plus).', [{ quand: 'degat_recu', faire: { type: 'bonus', bonus: { s: 'degats', a: 0.8 }, duree: 'salle', cumulMax: 3 } }], { ensemble: 'renard', icone: ic('tete_renard', '#c83a2a', '#8a1a1a', '#ffe060') });
  O('PSV_133', 'Volonté du feu', 'contrepartie', 2, 'H1 A1', 'Avec deux demi-unités ou moins, dégâts +2.', [{ quand: 'degat_recu', si: 'santeBasse', faire: { type: 'bonus', bonus: { s: 'degats', a: 2 }, duree: 'salle', cumulMax: 1 } }], { icone: ic('flamme', '#f08a24', '#c83018', '#ffe060') });
  O('PSV_134', 'Colère de la Racine', 'contrepartie', 2, 'P1 H1', 'Les ennemis tués lâchent parfois un demi-chakra instable (5 %).', [{ quand: 'elimination', si: 'ennemiNonBoss', chance: 0.05, faire: { type: 'protection', demis: 1, instable: true } }], { icone: ic('masque', '#2a2a34', '#e8e4dc', '#1c1420') });
  O('PSV_135', 'Rituel du sang', 'contrepartie', 2, 'P2', 'Chaque tribut volontaire donne +0,25 dégâts permanents.', [{ quand: 'sacrifice', faire: { type: 'bonus_permanent', bonus: { s: 'degats', a: 0.25 } } }], { ensemble: 'interdit', icone: ic('goutte', '#a01020', '#5a0a10', '#ff8a8a') });
  O('PSV_136', 'Écailles de Samehada', 'contrepartie', 3, 'H1 B1 P1', 'Toutes les 12 éliminations, soigne une demi-unité ; dégâts +0,5.', [{ quand: 'elimination', tousLes: 12, faire: { type: 'soin', demis: 1 } }, s('degats', 0.5)], { statut: 'adaptation', icone: ic('epee', '#4a6a8a', '#e8f0f8', '#34506a') });
  O('PSV_137', 'Cadence frénétique', 'contrepartie', 2, 'H1 P1', 'Cadence ×1,4, dégâts −10 %.', [sm('cadence', 1.4), sp('degats', -10)], { icone: ic('eclair', '#f0f060', '#e05a2a', '#ffffff'), contrepartie: 'Dégâts −10 %.' });
  O('PSV_138', 'Silence de la brume', 'contrepartie', 2, 'H1 C1', 'En entrant dans une salle, les ennemis vous perdent de vue 2 s.', [{ quand: 'entree_salle', si: 'combat', faire: { type: 'invisibilite', duree: 2 } }], { icone: ic('goutte', '#a8b8c8', '#6a7a8a', '#ffffff') });
  O('PSV_139', 'Transfert du pacte', 'contrepartie', 2, 'P1', 'Chaque pacte conclu : +1 dégât permanent.', [{ quand: 'cout_paye', faire: { type: 'bonus_permanent', bonus: { s: 'degats', a: 1 } } }], { ensemble: 'interdit', icone: ic('crane', '#6a2a8a', '#2a1040', '#e060ff') });
  O('PSV_140', 'Réincarnation impure (empreinte)', 'contrepartie', 3, 'P2', '10 % des ennemis tués reviennent comme alliés 10 s.', [{ quand: 'elimination', si: 'ennemiNonBoss', chance: 0.1, faire: { type: 'allie', duree: 10 } }], { statut: 'adaptation (attribution à vérifier)', ensemble: 'experimental', icone: ic('rouleau', '#3a2a3a', '#a08ab0', '#e8e0d0') });
  O('PSV_141', 'Cœur du réceptacle', 'contrepartie', 2, 'B2', 'Chaque boss vaincu donne un contenant de vitalité.', [{ quand: 'boss_vaincu', faire: { type: 'ressource_sante' } }], { icone: ic('coeur', '#f08a24', '#c8661a', '#ffe060') });
  O('PSV_142', 'Main du scorpion', 'contrepartie', 1, 'H1 P1', 'Le poison dure deux fois plus ; 10 % d’empoisonner.', [{ drapeau: 'poisonLong' }, { statut: 'poison', chance: 0.1, chanceParChance: 0.02, max: 0.4 }], { ensemble: 'marionnette', icone: ic('gant', '#6a3a8a', '#3a2a4a', '#7ae04a') });
  O('PSV_143', 'Mue du serpent', 'contrepartie', 3, 'P1 B1', 'Une fois par étage, quand votre dernière réserve de chakra se brise, vous gagnez une réserve.', [{ quand: 'degat_recu', faire: { type: 'mue' } }], { ensemble: 'experimental', icone: ic('serpent', '#e8e4d0', '#b8b4a0', '#6a2a8a') });
  O('PSV_144', 'Nature du sage', 'hybride', 3, 'A1 L1', 'Immobile une seconde, vous accumulez l’énergie naturelle : dégâts ×1,5 jusqu’au prochain pas.', [{ drapeau: 'energieNaturelle' }], { ensemble: 'ermite', icone: ic('crapaud', '#8a9a4a', '#f08a24', '#1c1420'), visuel: { couche: 'peau', motif: 'maquillage', couleur: '#f08a24', prio: 3 } });
  O('PSV_145', 'Pluie d’armes', 'hybride', 3, 'H1 L1 B1', 'Tous les 5 cycles de tir, huit armes tombent du ciel sur les ennemis.', [{ quand: 'emission_primaire', tousLes: 5, faire: { type: 'pluie_armes', n: 8, coef: 1.5 } }], { statut: 'adaptation', icone: ic('epee', '#c8ccd8', '#c83a2a', '#6a4a2a') });
  O('PSV_146', 'Rasenshuriken (empreinte)', 'hybride', 4, 'B1 H1', 'Vos orbes et charges explosent en tourbillon de vent.', [{ impact: 'explosion', r: 1.6, coef: 0.8 }, { traj: 'percant' }, s('degats', 0.5), { element: 'futon' }], { statut: 'adaptation', ensemble: 'renard', icone: ic('fuma', '#e0f4ff', '#6ab8f8', '#ffffff') });
  O('PSV_147', 'Lance de foudre', 'hybride', 3, 'H1 B1', 'Un trait de foudre accompagne chaque tir (×0,5).', [{ forme: 'laser' }, { element: 'raiton' }], { statut: 'adaptation', ensemble: 'tonnerre', icone: ic('lame', '#a8d8ff', '#5a90d8', '#ffffff') });
  O('PSV_148', 'Double dragon', 'hybride', 3, 'H1 L1', 'Tir multiple et guidage léger réunis.', [{ multi: 1, coefCadence: 0.95 }, { traj: 'guidage', force: 0.6 }], { icone: ic('rouleau', '#6a9a3a', '#c83a2a', '#e8d0a0') });
  O('PSV_149', 'Explosion de chakra', 'hybride', 3, 'H1 P1', 'Les tirs explosent à l’impact (souffle léger, ne vous blesse pas).', [{ impact: 'explosion', r: 0.9, coef: 0.6 }, sp('degats', -10)], { ensemble: 'argile', icone: ic('etoile', '#ffb050', '#f07820', '#fff0c0') });
  O('PSV_150', 'Tempête de sable', 'hybride', 3, 'H1 B1', 'Tirs de sable qui ralentissent et tournent.', [{ traj: 'orbite' }, { statut: 'ralenti', chance: 0.35, duree: 2 }, s('degats', 0.5)], { ensemble: 'sable', icone: ic('tornade', '#d8b070', '#a8804a', '#f8e0a8') });
  O('PSV_151', 'Chakra partagé', 'hybride', 2, 'A1 H1', 'Vos familiers infligent 25 % de plus.', [{ drapeau: 'familiersForts' }], { ensemble: 'meute', icone: ic('etoile', '#8af07a', '#3a9a4a', '#ffffff') });
  O('PSV_152', 'Encre vivante', 'hybride', 2, 'L1 H1', 'Les ennemis tués laissent parfois un fauve d’encre pour la salle (10 %).', [{ quand: 'elimination', chance: 0.1, faire: { type: 'familier', familier: 'FAM_TIGRE_ENCRE', salle: true } }], { icone: ic('pinceau', '#1a1a2a', '#e8e0d0', '#6a6a88') });

  // ── Objets-clés de route (hors pools : jamais relancés ni retirés) ──
  O('PSV_900', 'Clé des ermites', 'exploration', 0, '', 'Objet-clé : ouvre le rayon de la Lumière même après un pacte.', [], { cle: true, cumul: 'unique', icone: ic('cle', '#fff8e0', '#e8e0c0', '#6a9a3a') });
  O('PSV_901', 'Fragment de la clé des ermites', 'exploration', 0, '', 'Objet-clé : un second fragment formera la clé.', [], { cle: true, cumul: 'conversion', icone: ic('cle', '#c8c0a0', '#8a8060', '#6a9a3a') });
  DON.objets.find(o => o.id === 'PSV_901').conversion = { res: { ryo: 5 } };
})();
