// ═══════════════════════════════════════════════════════════════════════════
// Techniques scellées (ACT) : charges = nombre de salles de combat nettoyées
// pour recharger (1 à 12) ; « recharge » = secondes en combat ; « unique ».
// ═══════════════════════════════════════════════════════════════════════════
(function () {
  const POOLS = { H: 'heritage', B: 'boss', S: 'boutique', P: 'pacte', A: 'sanctuaire', C: 'cache', I: 'isolee', L: 'bibliotheque', D: 'defi', K: 'coffre', M: 'machine' };
  const pools = t => { const o = {}; for (const m of t.split(' ').filter(Boolean)) o[POOLS[m[0]]] = +(m.slice(1) || 1); return o; };
  const ic = (forme, a, b, c) => ({ forme, a, b, c });
  const A = (id, nom, q, p, charges, effet, params, desc, x = {}) => DON.objets.push(Object.assign({ id, nom, type: 'actif', famille: 'actif', qualite: q, pools: pools(p), charges, effet, params, desc, statut: 'création originale', cumul: 'unique' }, x));

  A('ACT_001', 'Réécriture d’empreinte', 3, 'H1 S1 L1', 6, 'reecriture', {}, 'Relance les objets sur piédestal de la salle, chacun depuis son pool.', { icone: ic('rouleau', '#e8dcc0', '#3a3040', '#c83a2a'), sansCible: 'conserve' });
  A('ACT_002', 'Multi-clonage', 2, 'H1 S1', 4, 'clones', { n: 2 }, 'Deux clones copient vos tirs pour la salle (50 %) et disparaissent au premier coup.', { statut: 'adaptation', icone: ic('masque', '#f6cf3e', '#f28a22', '#28407c'), persoExclusif: null });
  A('ACT_003', 'Chidori', 3, 'H1 B1', 3, 'dash', { portee: 4, coef: 6, duree: 0.22, visuel: 'foudre' }, 'Fonce en ligne droite : 6× dégâts aux ennemis traversés, invulnérable pendant l’élan.', { statut: 'adaptation', ensemble: 'tonnerre', icone: ic('eclair', '#a8d8ff', '#5a90d8', '#ffffff') });
  A('ACT_004', 'Ōkashō', 2, 'H1', 3, 'okasho', { base: 12 }, 'Frappe le sol : 12 dégâts + 4 par point de force stocké, brise rochers et murs fissurés proches.', { statut: 'adaptation', icone: ic('poing', '#f39ab8', '#cf6a90', '#ffffff') });
  A('ACT_006', 'Invocation des chiens ninja', 2, 'H1 L1', 3, 'immobiliser_tous', { duree: 3, coef: 2, visuel: 'chiens' }, 'Des chiens surgissent et immobilisent tous les ennemis 3 s (boss : réduit).', { statut: 'adaptation', ensemble: 'meute', icone: ic('chien', '#c8a870', '#8a6a4a', '#1c1420') });
  A('ACT_007', 'Porte de l’Ouverture', 2, 'H1 B1', 3, 'bonus', { duree: 8, bonus: [{ s: 'degats', m: 1.5 }, { s: 'vitesse', a: 1 }, { s: 'cadence', m: 1.3 }], visuel: 'aura_verte', nom: 'portes' }, '8 s : dégâts ×1,5, vitesse +1, cadence ×1,3.', { statut: 'adaptation (Huit Portes)', ensemble: 'portes', icone: ic('poing', '#6ae07a', '#3a9a4a', '#ffffff') });
  A('ACT_008', 'Protection des huit trigrammes', 3, 'H1 A1', 2, 'kaiten', { duree: 1.2, coef: 6 }, 'Rotation de 1,2 s : détruit les tirs proches, repousse et blesse (6× dégâts au total).', { statut: 'adaptation (Hyūga)', ensemble: 'yeux', icone: ic('tornade', '#e0e8ff', '#a0b0d8', '#ffffff') });
  A('ACT_009', 'Manipulation des ombres', 2, 'H1 L1', 3, 'ombres', { n: 3, duree: 4 }, 'Immobilise les trois ennemis les plus proches pendant 4 s (boss : 1,4 s).', { statut: 'adaptation', icone: ic('racine', '#2a2238', '#1c1428', '#6a5a80') });
  A('ACT_010', 'Cercueil de sable', 3, 'H1 B1', 3, 'frappe_cible', { coef: 10, coefBoss: 6, delai: 0.5, visuel: 'cercueil', son: 'sable' }, 'Le sable écrase l’ennemi le plus proche : 10× dégâts (6× contre un boss).', { statut: 'adaptation', ensemble: 'sable', icone: ic('sable', '#c8a060', '#8a6a3a', '#f0d8a0') });
  A('ACT_011', 'Kuroari : piège', 2, 'H1 L1', 3, 'frappe_cible', { coef: 8, coefBoss: 3, delai: 1.2, capture: 1.2, visuel: 'cercueil', son: 'lame' }, 'Enferme l’ennemi non-boss le plus proche puis le transperce (8×).', { statut: 'adaptation', ensemble: 'marionnette', icone: ic('marionnette', '#2a2a30', '#6a6a78', '#1c1420') });
  A('ACT_012', 'Crocs sur crocs', 2, 'H1 S1', 3, 'dash', { portee: 6, coef: 5, duree: 0.4, visuel: 'vrille' }, 'Deux passes en vrille à travers la salle : 5× dégâts à chaque contact, invulnérable.', { statut: 'adaptation', ensemble: 'meute', icone: ic('tornade', '#c8c0b0', '#8a8070', '#ffffff') });
  A('ACT_013', 'Pluie de senbon empoisonnés', 2, 'H1 P1', 2, 'anneau_projectiles', { n: 16, coef: 2, statut: 'poison', apparence: 'senbon' }, 'Seize senbon empoisonnés partent en cercle.', { ensemble: 'marionnette', icone: ic('senbon', '#b070d0', '#5a2a7a', '#7ae04a') });
  A('ACT_014', 'Fils de Jiongu', 2, 'H1 P1', 2, 'attirer', {}, 'Attire tous les ramassables de la salle et lacère les ennemis proches (3×).', { statut: 'adaptation', icone: ic('chaine', '#2a2a2a', '#6a6a6a', '#c83a2a') });
  A('ACT_015', 'Parchemin de substitution', 2, 'H1 S1 A1', 2, 'substitution', { duree: 3 }, 'Une bûche prend votre place : 3 s d’invisibilité, les ennemis frappent la bûche.', { statut: 'adaptation (Kawarimi)', icone: ic('rouleau', '#8a5a30', '#c89a60', '#3a2a1a') });
  A('ACT_016', 'Invocation : grand crapaud', 4, 'A1 B1 P1', 6, 'gamabunta', {}, 'Un crapaud géant atterrit : 40 dégâts à tous les ennemis (25 aux boss), obstacles pulvérisés.', { statut: 'adaptation', ensemble: 'ermite', icone: ic('crapaud', '#d86a2a', '#f0b070', '#3a1a10') });
  A('ACT_017', 'Amaterasu (empreinte)', 3, 'P2', 4, 'statut_tous', { statut: 'brulure', duree: 3, coef: 3, visuel: 'flammes_noires', son: 'feu' }, 'Flammes noires sur tous les ennemis de la salle.', { statut: 'adaptation (attribution à vérifier)', ensemble: 'yeux', icone: ic('flamme', '#1a0a1a', '#5a2a6a', '#b060ff') });
  A('ACT_018', 'Tsukuyomi (empreinte)', 4, 'P1 B1', 6, 'tsukuyomi', { duree: 4 }, 'Le temps s’arrête pour vos ennemis et leurs tirs pendant 4 s (boss : 1,5 s).', { statut: 'adaptation (attribution à vérifier)', ensemble: 'yeux', icone: ic('lune', '#c81e28', '#6a0a14', '#1c1420') });
  A('ACT_019', 'Répulsion divine', 3, 'P1 B1', 3, 'repousser', { coef: 3 }, 'Repousse tous les ennemis, détruit tous leurs tirs, 3× dégâts.', { statut: 'adaptation', icone: ic('sphere', '#e0e0ff', '#a0a0d8', '#ffffff') });
  A('ACT_020', 'Attraction céleste', 3, 'P1 B1', 4, 'attraction', { coef: 5 }, 'Attire les ennemis au centre puis les écrase (5×).', { statut: 'adaptation', icone: ic('sphere', '#2a2030', '#6a5a80', '#c0b0e0') });
  A('ACT_021', 'Espace-temps intangible', 3, 'P1 I1', 4, 'kamui', { duree: 3 }, '3 s intangible : ennemis et tirs vous traversent (pas les murs) ; vous ne pouvez pas tirer.', { statut: 'adaptation', icone: ic('sceau', '#e87a2a', '#1c1420', '#a8a8b0') });
  A('ACT_022', 'Pilule du soldat', 1, 'S2 H1', 1, 'bonus', { duree: 'salle', bonus: { s: 'cadence', a: 1 }, visuel: 'aura_verte' }, 'Pour la salle : cadence +1.', { statut: 'adaptation', icone: ic('pilule', '#f0e8a0', '#c8b050', '#ffffff') });
  A('ACT_023', 'Parchemin de téléportation', 1, 'S1 H1', 2, 'teleport', {}, 'Vous téléporte dans une salle déjà visitée.', { icone: ic('rouleau', '#8a7ab0', '#e8dcc0', '#3a3040'), sansCible: 'conserve' });
  A('ACT_024', 'Rasenshuriken', 4, 'B1 H1', 4, 'rasenshuriken', {}, 'Un immense shuriken de vent traverse tout et explose (15× autour).', { statut: 'adaptation', ensemble: 'renard', icone: ic('fuma', '#e0f4ff', '#6ab8f8', '#ffffff') });
  A('ACT_025', 'Dragons de feu', 3, 'H1 B1', 3, 'dragons', {}, 'Quatre dragons de feu chercheurs (4×, brûlure).', { icone: ic('flamme', '#c83018', '#f07820', '#ffe060') });
  A('ACT_026', 'Forêt naissante', 3, 'A1 B1', 4, 'racines', {}, 'Des racines jaillissent sous chaque ennemi : immobilisation 2,5 s et dégâts répétés.', { statut: 'adaptation (Mokuton)', icone: ic('racine', '#6a4a2a', '#4a3018', '#8ac060') });
  A('ACT_027', 'Sceau de scellement', 4, 'L1 A1', 6, 'scellement', {}, 'Scelle l’ennemi le plus proche (boss : 15 % de ses PV).', { icone: ic('sceau', '#e8d060', '#8a6a20', '#1c1420') });
  A('ACT_028', 'Invocation inversée', 2, 'L1 H1', 3, 'familier_temporaire', {}, 'Invoque un familier au hasard pour tout l’étage.', { icone: ic('rouleau', '#6a9a3a', '#e8dcc0', '#3a3040') });
  A('ACT_029', 'Transfert d’esprit', 3, 'L1 H1', 3, 'charme', {}, 'L’ennemi non-boss le plus proche combat pour vous jusqu’à sa mort.', { statut: 'adaptation', icone: ic('feuille', '#e8a0d0', '#a05090', '#ffffff') });
  A('ACT_030', 'Lotus primaire', 2, 'H1 D1', 2, 'lotus', {}, 'Saisit l’ennemi proche : 12× dégâts ; vous coûte une demi-unité si vous en avez plus d’une.', { statut: 'adaptation', ensemble: 'portes', icone: ic('feuille', '#6ae07a', '#3a9a4a', '#e0ffe0') });
  A('ACT_031', 'Rituel de permutation', 3, 'P1 C1', 0, 'permutation', {}, 'Usage unique : chaque passif (hors objets-clés) est remplacé par un autre.', { unique: true, icone: ic('sceau', '#6a2a8a', '#e8dcc0', '#c83a2a') });
  A('ACT_032', 'Genjutsu du temps suspendu', 2, 'L1 S1', 4, 'ralentir_tous', { duree: 6 }, 'Ralentit tous les ennemis de moitié pendant 6 s.', { icone: ic('lune', '#6a80c0', '#3a4a8a', '#e0e8ff') });
  A('ACT_033', 'Sablier du courant', 2, 'H1 L1', 0, 'bonus', { duree: 6, bonus: { s: 'vitesse', a: 1.2 } }, 'Recharge dans le temps (20 s en combat) : 6 s de vitesse +1,2.', { recharge: 20, icone: ic('fiole', '#6ac8e8', '#3a8ab0', '#ffffff') });
  A('ACT_050', 'Relais', 0, '', 1, 'relais', {}, 'Sacrifie un clone : explosion de chakra (5× dégâts autour).', { persoExclusif: 'ALT_001', icone: ic('masque', '#6a2a1a', '#f28a22', '#28407c') });
  // un seul objet actif par identifiant ; les actifs comptent dans les transformations dès leur première prise
})();
