// ═══════════════════════════════════════════════════════════════════════════
// Transformations (TRF), synergies documentées (SYN), objectifs (OBJ),
// défis (DEF) et secrets (SEC). Les synergies « émergentes » découlent des
// règles générales du pipeline de tir ; les « dédiées » ajoutent un effet.
// ═══════════════════════════════════════════════════════════════════════════
(function () {
  // ── Résonances de chakra : 3 identifiants distincts d'un ensemble ──
  const TR = (id, nom, ensemble, desc, effets, visuel, x = {}) => DON.transformations.push(Object.assign({ id, nom, type: 'transformation', ensemble, seuil: 3, desc, effets, visuel, statut: 'création originale' }, x));
  TR('TRF_001', 'Manteau du renard', 'renard', 'Aura de chakra : les ennemis à votre contact brûlent ; dégâts +1.', [{ s: 'degats', a: 1 }, { drapeau: 'auraContact' }, { statut: 'brulure', chance: 0.15, max: 0.15 }], { couche: 'aura', motif: 'queues', n: 3, couleur: '#f0a030' }, { icone: { forme: 'tete_renard', a: '#f08a24' } });
  TR('TRF_002', 'Sage imparfait', 'ermite', 'Immobile 0,6 s : dégâts ×1,6 jusqu’au prochain pas ; portée +2.', [{ drapeau: 'energieNaturelle' }, { drapeau: 'sageFort' }, { s: 'portee', a: 2 }], { couche: 'peau', motif: 'maquillage', couleur: '#f08a24' }, { icone: { forme: 'crapaud', a: '#8a9a4a' } });
  TR('TRF_003', 'Essaim Aburame', 'essaim', 'Vos tirs deviennent des insectes chercheurs ; un essaim vous accompagne.', [{ traj: 'guidage', force: 1.5 }, { apparence: 'insecte' }, { familier: 'FAM_INSECTES' }], { couche: 'aura', motif: 'insectes' }, { icone: { forme: 'insecte', a: '#3a3a2a' } });
  TR('TRF_004', 'Arsenal du marionnettiste', 'marionnette', 'Une marionnette d’attaque supplémentaire ; vos marionnettes frappent 50 % plus fort.', [{ familier: 'FAM_KARASU_ATT' }, { drapeau: 'marionnettesFortes' }], { couche: 'bras', motif: 'bras_marionnette' }, { icone: { forme: 'marionnette', a: '#6a5a4a' } });
  TR('TRF_005', 'Résonance des yeux', 'yeux', 'Barres de vie ennemies visibles, fissures des murs secrets révélées, chance +2, léger guidage.', [{ drapeau: 'indicesSecrets' }, { s: 'chance', a: 2 }, { traj: 'guidage', force: 0.5 }], { couche: 'yeux', motif: 'yeux_rouges', couleur: '#e0202a' }, { icone: { forme: 'oeil', a: '#e8e8f0', b: '#c81e28' } });
  TR('TRF_006', 'Armure de sable', 'sable', 'Trois orbitaux de sable ; les coups d’un cœur entier ne retirent qu’une demi-unité.', [{ familier: 'FAM_SABLE' }, { familier: 'FAM_SABLE' }, { familier: 'FAM_SABLE' }, { drapeau: 'armureSable' }], { couche: 'aura', motif: 'sable_flottant' }, { icone: { forme: 'sable', a: '#d8b070' } });
  TR('TRF_007', 'Reliques interdites', 'interdit', 'Lévitation, deux réserves instables, dégâts +1.', [{ vol: true }, { sante: { instable: 4 } }, { s: 'degats', a: 1 }], { couche: 'tete', motif: 'cornes', couleur: '#3a1a4a' }, { icone: { forme: 'crane', a: '#3a1a4a' } });
  TR('TRF_008', 'Outils du tonnerre', 'tonnerre', 'Chaque tir enchaîne la foudre sur un ennemi proche ; cadence +0,3.', [{ impact: 'chaine', sauts: 1, r: 3, coef: 0.5 }, { s: 'cadence', a: 0.3 }, { element: 'raiton' }], { couche: 'aura', couleur: '#a0d0ff' }, { icone: { forme: 'eclair', a: '#a8d8ff' } });
  TR('TRF_009', 'Corps expérimental', 'experimental', 'Un contenant de plus ; blessé, deux serpents vous défendent pour la salle.', [{ sante: { cont: 1 } }, { quand: 'degat_recu', faire: { type: 'familier', familier: 'FAM_SERPENT_BLANC', salle: true } }], { couche: 'peau', motif: 'marque', couleur: '#6a2a8a' }, { icone: { forme: 'serpent', a: '#e8e4d0' } });
  TR('TRF_010', 'Messager de papier', 'papier', 'Lévitation, quatre papillons protecteurs, tirs de papier.', [{ vol: true }, { familier: 'FAM_PAPIER' }, { familier: 'FAM_PAPIER' }, { apparence: 'papier' }], { couche: 'dos', motif: 'plumes', couleur: '#f4f0e8' }, { icone: { forme: 'papier', a: '#f4f0e8' } });
  TR('TRF_011', 'Meute d’invocation', 'meute', 'Deux compagnons supplémentaires ; tous les familiers +25 %.', [{ familier: 'FAM_TIGRE_ENCRE' }, { familier: 'FAM_AKAMARU' }, { drapeau: 'familiersForts' }], { couche: 'corps', motif: 'bandeau_bras', couleur: '#c83a2a' }, { icone: { forme: 'chien', a: '#c8a870' } });
  TR('TRF_012', 'Huit Portes', 'portes', 'Plafond de cadence +1, vitesse +0,5, dégâts +1 ; vapeur verte.', [{ s: 'plafondCadence', a: 1 }, { s: 'vitesse', a: 0.5 }, { s: 'degats', a: 1 }], { couche: 'aura', couleur: '#8af07a' }, { icone: { forme: 'poing', a: '#6ae07a' } });
  TR('TRF_013', 'Artiste explosif', 'argile', 'Vos tirs explosent légèrement ; vos explosions ne vous blessent plus.', [{ impact: 'explosion', r: 0.8, coef: 0.4 }, { drapeau: 'immuniteExplosion' }], { couche: 'bras', motif: 'lueur_poings', couleur: '#f0e8d8' }, { icone: { forme: 'oiseau', a: '#f0e8d8' } });

  // ── Synergies documentées ──
  const SY = (id, nom, composants, type, desc, test, effets) => DON.synergies.push({ id, nom, composants, type, desc, test, effets: effets || [] });
  SY('SYN_001', 'Rasengan jumeau', ['PSV_001', 'PSV_002'], 'emergente', 'Deux sphères partagent la charge : 3,5 × 3 × 0,70 = 7,35 dégâts chacune ; cycle 0,6 / 0,9 ≈ 0,667 s.', 'Cible immobile : deux sphères, dégâts et cycle attendus, arrêt au mur, rien au changement de salle.');
  SY('SYN_002', 'Sphère chercheuse', ['PSV_001', 'PSV_005'], 'emergente', 'Les sphères chargées se guident vers la cible.', 'Cible latérale touchée sans alignement parfait.');
  SY('SYN_003', 'Sphère orageuse', ['PSV_001', 'PSV_028'], 'emergente', 'Chaque sphère enchaîne la foudre sur deux ennemis.', 'Groupe de trois : trois cibles blessées par une sphère.');
  SY('SYN_004', 'Tourbillon de vent complet', ['PSV_001', 'PSV_146'], 'dediee', 'L’explosion de vent des sphères s’élargit (rayon 2).', 'Rayon d’explosion mesuré à 2 tuiles.', [{ impact: 'explosion', r: 2, coef: 0.4 }]);
  SY('SYN_005', 'Canons en éventail', ['PSV_014', 'PSV_003'], 'emergente', 'Trois rayons en éventail, chacun au coefficient de multitir (0,58).', 'Trois faisceaux, dégâts par rayon = 58 %.');
  SY('SYN_006', 'Rayon perçant', ['PSV_014', 'PSV_008'], 'dediee', 'Le rayon traverse déjà tout : le percement devient +20 % de dégâts.', 'Dégâts par tic ×1,2.', [{ coefDegats: 1.2 }]);
  SY('SYN_007', 'Retour guidé', ['PSV_013', 'PSV_005'], 'emergente', 'Le fūma suit sa cible à l’aller, puis revient.', 'Trajet courbe puis retour à la main.');
  SY('SYN_008', 'Fūma foudroyant', ['PSV_013', 'PSV_028'], 'emergente', 'Chaque passage du fūma enchaîne la foudre.', 'Deux chaînes par lancer (aller et retour).');
  SY('SYN_009', 'Argile incendiaire', ['PSV_019', 'PSV_043'], 'dediee', 'Les bombes d’argile laissent des flammes alliées.', 'Zone de feu après chaque explosion.', [{ impact: 'flamme' }]);
  SY('SYN_010', 'Météore gelé', ['PSV_020', 'PSV_050'], 'dediee', 'Les frappes au sol gèlent à coup sûr.', 'Ennemi gelé après une frappe.', [{ statut: 'gel', chance: 1, duree: 1.5 }]);
  SY('SYN_011', 'Sphère d’encre', ['PSV_021', 'PSV_052'], 'dediee', 'La sphère guidée charme plus souvent (+20 %).', 'Charme observé en moins de 10 contacts.', [{ statut: 'charme', chance: 0.2, duree: 3 }]);
  SY('SYN_012', 'Souffle du vent', ['PSV_016', 'PSV_046'], 'dediee', 'Le faisceau continu porte deux tuiles plus loin.', 'Longueur du faisceau +2 tuiles.', [{ s: 'portee', a: 2 }]);
  SY('SYN_013', 'Tempête orbitale', ['PSV_010', 'PSV_065'], 'dediee', 'Un orbital de sable supplémentaire.', 'Trois orbitaux.', [{ familier: 'FAM_SABLE' }]);
  SY('SYN_014', 'Ricochet détonant', ['PSV_007', 'PSV_149'], 'dediee', 'Un ricochet de plus ; l’explosion survient au dernier contact.', 'Trois ricochets puis explosion.', [{ traj: 'rebond' }]);
  SY('SYN_015', 'Mille aiguilles empoisonnées', ['PSV_004', 'PSV_048'], 'dediee', 'Poison +20 %.', 'Taux de poison sur 50 tirs.', [{ statut: 'poison', chance: 0.2 }]);
  SY('SYN_016', 'Éventail de feu', ['PSV_003', 'PSV_043'], 'dediee', 'Brûlure +10 %.', 'Taux de brûlure sur 50 tirs.', [{ statut: 'brulure', chance: 0.1 }]);
  SY('SYN_017', 'Le vent attise le feu', ['PSV_043', 'PSV_046'], 'dediee', 'Les impacts laissent des flammes ; dégâts +0,5.', 'Zones de feu à l’impact.', [{ impact: 'flamme' }, { s: 'degats', a: 0.5 }]);
  SY('SYN_018', 'Eau conductrice', ['PSV_044', 'PSV_045'], 'dediee', 'La foudre se propage par l’eau : un saut de chaîne.', 'Chaîne vers un ennemi proche.', [{ impact: 'chaine', sauts: 1, r: 2.5, coef: 0.4 }]);
  SY('SYN_019', 'Boue', ['PSV_047', 'PSV_044'], 'dediee', 'Ralentissement +30 %.', 'Taux de ralenti.', [{ statut: 'ralenti', chance: 0.3, duree: 2 }]);
  SY('SYN_020', 'Ombre lestée', ['PSV_051', 'PSV_034'], 'dediee', 'Immobilisation +10 %.', 'Taux d’immobilisation.', [{ statut: 'immobilise', chance: 0.1, duree: 1.2 }]);
  SY('SYN_021', 'Clones à l’encre', ['PSV_061', 'PSV_002'], 'dediee', 'Un second clone rejoint le premier.', 'Deux clones suiveurs.', [{ familier: 'FAM_CLONE' }]);
  SY('SYN_022', 'Flair de la meute', ['PSV_068', 'PSV_069'], 'dediee', 'Toutes les 6 salles nettoyées, les chiens déterrent une ressource.', 'Ressource à la 6e salle.', [{ quand: 'salle_nettoyee', tousLes: 6, faire: { type: 'ramassable', ramassable: 'coffre' } }]);
  SY('SYN_023', 'Envolée d’argile', ['PSV_019', 'PSV_071'], 'dediee', 'L’oiseau d’argile se recharge deux fois plus vite.', 'Plongeon toutes les 2 s.', [{ drapeau: 'oiseauRapide' }]);
  SY('SYN_024', 'Grand sabre vorace', ['PSV_136', 'PSV_017'], 'dediee', 'Soin toutes les 8 éliminations au lieu de 12.', 'Soin à la 8e élimination.', [{ quand: 'elimination', tousLes: 8, faire: { type: 'soin', demis: 1 } }]);
  SY('SYN_025', 'Malédiction partagée', ['PSV_091', 'PSV_054'], 'dediee', 'La marque de Jashin inflige 10 dégâts de plus.', 'Dégâts de salle 25.', [{ quand: 'degat_recu', faire: { type: 'degats_tous', degats: 10 } }]);
  SY('SYN_026', 'Rotation clairvoyante', ['PSV_113', 'PSV_022'], 'dediee', 'La rotation couvre une portée plus large.', 'Rayon de rotation +0,5 tuile.', [{ s: 'portee', a: 1 }]);
  SY('SYN_027', 'Miroirs gelés', ['PSV_050', 'PSV_081'], 'emergente', 'Les tirs renvoyés par les miroirs sont de glace (élément hyoton).', 'Tir renvoyé gèle parfois.');
  SY('SYN_028', 'Lames tournoyantes', ['PSV_018', 'PSV_022'], 'emergente', 'Frappe courte + rotation : la rotation domine, la lame devient un coup d’appoint.', 'Priorité rotation, coup d’appoint présent.');
  SY('SYN_029', 'Laser en éventail', ['PSV_015', 'PSV_003'], 'emergente', 'Trois traits instantanés.', 'Trois lignes par cycle.');
  SY('SYN_030', 'Faisceau ondulant', ['PSV_016', 'PSV_011'], 'emergente', 'Le faisceau ignore l’ondulation (trajectoire d’un faisceau) : l’onde devient +0,3 dégâts seulement.', 'Pas de déformation du faisceau.');
  SY('SYN_031', 'Frappe de sabre explosive', ['PSV_017', 'PSV_149'], 'emergente', 'Chaque coup de sabre déclenche l’explosion d’impact.', 'Explosion au contact du sabre.');
  SY('SYN_032', 'Orbe lent chercheur', ['PSV_012', 'PSV_006'], 'emergente', 'Énormes insectes lents qui traquent.', 'Guidage visible sur tirs lents.');
  SY('SYN_033', 'Orbite empoisonnée', ['PSV_010', 'PSV_048'], 'emergente', 'Les tirs en orbite empoisonnent au passage.', 'Poison sur ennemi au contact de l’orbite.');
  SY('SYN_034', 'Contrôle multiple', ['PSV_021', 'PSV_002'], 'emergente', 'La sphère guidée gagne le coefficient de multitir total (1,4×).', 'Dégâts de contact ×1,4.');
  SY('SYN_035', 'Frappe au sol multiple', ['PSV_020', 'PSV_003'], 'emergente', 'Le météore reste unique : le multitir ne multiplie pas la frappe (règle affichée), il n’a pas d’effet.', 'Une seule frappe par cycle.');
  SY('SYN_036', 'Bombes en salve', ['PSV_019', 'PSV_024'], 'emergente', 'Trois bombes par cycle, plus faibles (0,6).', 'Trois explosions échelonnées.');
  SY('SYN_037', 'Croix de foudre', ['PSV_026', 'PSV_028'], 'emergente', 'Les tirs en croix enchaînent aussi la foudre.', 'Chaînes dans quatre directions.');
  SY('SYN_038', 'Mines éclatantes', ['PSV_027', 'PSV_030'], 'emergente', 'Les mines ne se divisent pas (génération bornée) : l’éclat ne s’applique qu’aux tirs primaires.', 'Aucun éclat issu d’une mine.');
  SY('SYN_039', 'Boomerang explosif', ['PSV_013', 'PSV_149'], 'emergente', 'Chaque contact du fūma explose (budget par cycle : 14 déclenchements).', 'Nombre d’explosions ≤ 14 par lancer.');
  SY('SYN_040', 'Taijutsu enflammé', ['PSV_018', 'PSV_043'], 'emergente', 'La frappe courte applique la brûlure du Katon.', 'Brûlure sur frappe.');
  SY('SYN_041', 'Rotation et miroirs', ['PSV_022', 'PSV_081'], 'emergente', 'Défense quasi totale mais sans tir à distance : les miroirs ne bloquent qu’au contact (fréquence bornée).', 'Quelques tirs passent encore.');
  SY('SYN_042', 'Coups de sable', ['PSV_150', 'PSV_065'], 'emergente', 'Tempête de sable + orbitaux : couverture défensive dense.', 'Projectiles ennemis interceptés.');
  SY('SYN_043', 'Nuée d’encre', ['PSV_052', 'PSV_076'], 'emergente', 'Les fauves d’encre profitent des ennemis charmés.', 'Ennemis charmés attaqués.');
  SY('SYN_044', 'Voleur de pacte', ['PSV_129', 'PSV_107'], 'emergente', 'Payer ses pactes en Ryō avec une bourse qui double parfois les pièces.', 'Achat d’un pacte en Ryō.');
  SY('SYN_045', 'Marchand avisé', ['PSV_121', 'PSV_124'], 'emergente', 'Soldes et étal supplémentaire : l’échoppe devient une salle d’héritage payante.', 'Trois objets à moitié prix.');
  SY('SYN_046', 'Économie de relance', ['ACT_001', 'PSV_127'], 'emergente', 'Relances qui ne descendent jamais en qualité.', 'Qualité ≥ initiale après relance.');
  SY('SYN_047', 'Sceau éternel', ['PSV_095', 'PSV_083'], 'emergente', 'Sceaux partiels + soins : la vitalité monte d’étage en étage.', 'Contenant ajouté à l’étage suivant.');
  SY('SYN_048', 'Réserve inépuisable', ['PSV_087', 'PSV_093'], 'emergente', 'Régénération doublée par le chakra de la limace.', 'Soin de 2 demis toutes les 3 salles.');
  SY('SYN_049', 'Protection du démon', ['PSV_098', 'PSV_056'], 'emergente', 'Réserves instables + bulle rouge : chaque rupture déclenche aussi huit tirs.', 'Impulsion + huit tirs.');
  SY('SYN_050', 'Substitution et appât', ['PSV_096', 'PSV_080'], 'emergente', 'Deux sources d’esquive indépendantes (bûche puis poupée).', 'Coups évités cumulés.');
  SY('SYN_051', 'Lévitation minée', ['PSV_115', 'PSV_027'], 'emergente', 'Au-dessus des fosses, vos mines restent au-dessus du vide (elles fonctionnent).', 'Mine active au-dessus d’une fosse.');
  SY('SYN_052', 'Sage des crapauds', ['PSV_144', 'PSV_062'], 'emergente', 'Immobile, Gamakichi et vous frappez plus fort.', 'Bonus ×1,5 actif à l’arrêt.');
  SY('SYN_053', 'Portes et lotus', ['PSV_092', 'ACT_030'], 'emergente', 'Le lotus coûte de la santé : dangereux avec un contenant en moins.', 'Coût payé, pas un dommage.');
  SY('SYN_054', 'Fil et fūma', ['PSV_007', 'PSV_013'], 'emergente', 'Le fūma revient déjà : le ricochet ajoute trois rebonds à l’aller.', 'Rebonds avant retour.');
  SY('SYN_055', 'Arsenal complet', ['PSV_024', 'PSV_004'], 'emergente', 'Salves de quatre senbon : couverture maximale, dégâts unitaires faibles.', 'Douze projectiles par cycle.');
  SY('SYN_056', 'Canon et sceau de la mort', ['PSV_014', 'PSV_131'], 'emergente', 'Rayon ×2 de dégâts, santé réduite : combinaison volontairement dominante mais fragile.', 'Dégâts doublés, deux contenants de moins.');
  SY('SYN_057', 'Frappe céleste guidée', ['PSV_020', 'PSV_005'], 'emergente', 'Le réticule ne se guide pas (règle) : le guidage n’a pas d’effet sur la frappe.', 'Réticule inchangé.');
  SY('SYN_058', 'Clone de relais armé', ['PSV_023', 'PSV_028'], 'emergente', 'Le clone copie les impacts : sa foudre s’enchaîne aussi (génération 1).', 'Chaîne issue du clone.');
  SY('SYN_059', 'Onde et chaîne', ['PSV_029', 'PSV_028'], 'emergente', 'Chaque impact : onde puis chaîne (budget partagé).', 'Deux effets secondaires par impact.');
  SY('SYN_060', 'Artiste complet', ['PSV_110', 'PSV_019'], 'emergente', 'Bombes d’argile sans risque pour vous (immunité aux explosions).', 'Aucun dégât subi par ses propres bombes.');

  // ── Objectifs (missions) : conditions → déblocages ──
  const OB = (id, nom, desc, condition, debloque, texte) => DON.objectifs.push({ id, nom, desc, condition, recompense: { debloque: debloque || [], texte } });
  OB('OBJ_001', 'Premier sceau brisé', 'Vaincre un boss d’étage 1.', { type: 'compteur', nom: 'bossVaincus', min: 1 }, ['PSV_026', 'PSV_027'], 'Croix de sceaux, Parchemins-pièges');
  OB('OBJ_002', 'Le traître démasqué', 'Vaincre Mizuki.', { type: 'boss', id: 'BOS_001' }, ['PSV_013'], 'Fūma shuriken');
  OB('OBJ_003', 'Hors de la forêt', 'Vaincre le Serpent géant.', { type: 'boss', id: 'BOS_002' }, ['PSV_064', 'PSV_078'], 'Serpents');
  OB('OBJ_004', 'Le démon du brouillard', 'Vaincre Zabuza.', { type: 'boss', id: 'BOS_004' }, ['CHR_004', 'PSV_017'], 'Kakashi, Kubikiribōchō');
  OB('OBJ_005', 'Miroirs brisés', 'Vaincre Haku.', { type: 'boss', id: 'BOS_005' }, ['PSV_081', 'PSV_050'], 'Miroirs de glace, Glace éternelle');
  OB('OBJ_006', 'Les frères démons', 'Vaincre les frères démons.', { type: 'boss', id: 'BOS_003' }, ['PSV_007'], 'Fil de chakra');
  OB('OBJ_007', 'Fils coupés', 'Vaincre Kankurō.', { type: 'boss', id: 'BOS_006' }, ['PSV_072', 'PSV_073', 'PSV_074'], 'Marionnettes');
  OB('OBJ_008', 'Trio dissonant', 'Vaincre le trio du Son.', { type: 'boss', id: 'BOS_007' }, ['PSV_029'], 'Poing de Doton');
  OB('OBJ_009', 'Le sable se tait', 'Vaincre Gaara.', { type: 'boss', id: 'BOS_009' }, ['CHR_005', 'PSV_097'], 'Rock Lee, Armure de sable absolue');
  OB('OBJ_010', 'Os brisés', 'Vaincre Kimimaro.', { type: 'boss', id: 'BOS_008' }, ['PSV_060', 'PSV_090'], 'Os');
  OB('OBJ_011', 'La carapace tombe', 'Vaincre Sasori.', { type: 'boss', id: 'BOS_010' }, ['PSV_142'], 'Main du scorpion');
  OB('OBJ_012', 'Regard perçant', 'Trouver 5 caches de renseignements (cumulé).', { type: 'compteur', nom: 'secretsTrouves', min: 5 }, ['CHR_006', 'PSV_113'], 'Hinata, Byakugan');
  OB('OBJ_013', 'Soigneur démasqué', 'Vaincre Kabuto.', { type: 'boss', id: 'BOS_011' }, ['PSV_087'], 'Sceau de régénération');
  OB('OBJ_014', 'Requin échoué', 'Vaincre Kisame.', { type: 'boss', id: 'BOS_012' }, ['PSV_136'], 'Écailles de Samehada');
  OB('OBJ_015', 'Stratégie de l’examen', 'Réussir 2 épreuves chūnin (cumulé).', { type: 'compteur', nom: 'epreuvesChunin', min: 2 }, ['CHR_007', 'PSV_051'], 'Shikamaru, Ombre liante');
  OB('OBJ_016', 'Rituel rompu', 'Vaincre Hidan.', { type: 'boss', id: 'BOS_013' }, ['PSV_054', 'PSV_135'], 'Marque de Jashin, Rituel du sang');
  OB('OBJ_017', 'Première fin', 'Vaincre Orochimaru.', { type: 'boss', id: 'BOS_014' }, ['PSV_143', 'ACT_031'], 'Mue du serpent, Rituel de permutation');
  OB('OBJ_018', 'Protection absolue', 'Posséder 3 réserves de chakra protecteur en même temps.', { type: 'etat', nom: 'protections3' }, ['CHR_008'], 'Gaara');
  OB('OBJ_019', 'L’art éclate', 'Vaincre Deidara.', { type: 'boss', id: 'BOS_015' }, ['PSV_019', 'PSV_071', 'PSV_110'], 'Argile');
  OB('OBJ_020', 'Au-delà de l’illusion', 'Vaincre Itachi.', { type: 'boss', id: 'BOS_016' }, ['PSV_053', 'ACT_017', 'ACT_018'], 'Flammes noires, Amaterasu, Tsukuyomi');
  OB('OBJ_021', 'Marionnettiste', 'Posséder 3 familiers en même temps.', { type: 'etat', nom: 'familiers3' }, ['CHR_009'], 'Kankurō');
  OB('OBJ_022', 'Cinq cœurs', 'Vaincre Kakuzu.', { type: 'boss', id: 'BOS_017' }, ['PSV_089', 'PSV_129'], 'Cœur volé, Contrat');
  OB('OBJ_023', 'La douleur apaisée', 'Vaincre Pain.', { type: 'boss', id: 'BOS_018' }, ['ACT_019', 'ACT_020'], 'Répulsion, Attraction');
  OB('OBJ_024', 'Compagnon fidèle', 'Nettoyer 30 salles avec des familiers (cumulé : 30 salles au total).', { type: 'compteur', nom: 'objetsPris', min: 15 }, ['CHR_010'], 'Kiba');
  OB('OBJ_025', 'Masque brisé', 'Vaincre Obito.', { type: 'boss', id: 'BOS_019' }, ['ACT_021'], 'Espace-temps intangible');
  OB('OBJ_026', 'Gardien apaisé', 'Vaincre le Gardien du Sceau.', { type: 'boss', id: 'BOS_020' }, ['ACT_016', 'PSV_115'], 'Grand crapaud, Lévitation');
  OB('OBJ_027', 'Maître des marionnettes', 'Vaincre Sasori sans subir de dégâts pendant le combat.', { type: 'boss', id: 'BOS_010', sansDegats: true }, ['CHR_011'], 'Sasori (expert)');
  OB('OBJ_028', 'Rival ancien', 'Vaincre Madara.', { type: 'boss', id: 'BOS_021' }, ['PSV_020', 'ACT_026'], 'Chute céleste, Forêt naissante');
  OB('OBJ_029', 'Dix queues', 'Vaincre l’empreinte des Dix Queues.', { type: 'boss', id: 'BOS_022' }, ['PSV_014'], 'Canon de chakra');
  OB('OBJ_030', 'Fortune', 'Posséder 50 Ryō en même temps.', { type: 'etat', nom: 'ryo50' }, ['CHR_012', 'PSV_121'], 'Kakuzu (expert), Carte de membre');
  OB('OBJ_031', 'Collectionneur', 'Posséder 12 objets passifs en même temps.', { type: 'etat', nom: 'objets12' }, ['PSV_126', 'PSV_120'], 'Livre de l’ermite, Collier');
  OB('OBJ_032', 'Premier pacte', 'Conclure un pacte interdit.', { type: 'compteur', nom: 'pactes', min: 1 }, ['PSV_091', 'PSV_139'], 'Sceau maudit, Transfert du pacte');
  OB('OBJ_033', 'Explorateur', 'Détruire 10 rochers à sceau (cumulé).', { type: 'compteur', nom: 'rochersSceau', min: 10 }, ['PSV_114', 'PSV_106'], 'Voies secrètes, Épingle');
  OB('OBJ_034', 'Métamorphose', 'Obtenir une transformation.', { type: 'compteur', nom: 'transformations', min: 1 }, ['PSV_146', 'PSV_152'], 'Rasenshuriken, Encre vivante');
  OB('OBJ_035', 'Client fidèle', 'Faire 15 achats (cumulé).', { type: 'compteur', nom: 'achats', min: 15 }, ['PSV_124', 'PSV_122'], 'Réputation, Coupon');
  OB('OBJ_036', 'Donateur', 'Donner 50 Ryō à la caisse des marchands.', { type: 'compteur', nom: 'dons', min: 50 }, ['PSV_123'], 'Livret d’épargne ; échoppe niveau 1');
  OB('OBJ_037', 'Technique scellée', 'Utiliser 30 fois un actif (cumulé).', { type: 'compteur', nom: 'actifsUtilises', min: 30 }, ['ACT_024', 'ACT_027'], 'Rasenshuriken, Scellement');
  OB('OBJ_038', 'Chasseur', 'Éliminer 500 ennemis (cumulé).', { type: 'compteur', nom: 'eliminations', min: 500 }, ['PSV_145', 'ACT_025'], 'Pluie d’armes, Dragons de feu');
  OB('OBJ_039', 'Deuxième fin', 'Accomplir la deuxième fin (étage 8).', { type: 'fin', route: 'RTE_02' }, ['PSV_131', 'ACT_029'], 'Sceau de la mort, Transfert d’esprit');
  OB('OBJ_040', 'Réceptacle', 'Accomplir la première fin avec Naruto.', { type: 'fin', route: 'RTE_01', perso: 'CHR_001' }, ['ALT_001'], 'Naruto — Réceptacle fissuré');
  OB('OBJ_041', 'Vengeance', 'Accomplir la première fin avec Sasuke.', { type: 'fin', route: 'RTE_01', perso: 'CHR_002' }, ['ALT_002'], 'Sasuke — Serment de vengeance');
  OB('OBJ_042', 'Centaine', 'Accomplir la première fin avec Sakura.', { type: 'fin', route: 'RTE_01', perso: 'CHR_003' }, ['ALT_003'], 'Sakura — Sceau de la centaine');
  OB('OBJ_043', 'Shukaku', 'Accomplir la première fin avec Gaara.', { type: 'fin', route: 'RTE_01', perso: 'CHR_008' }, ['ALT_004'], 'Gaara — Shukaku déchaîné');
  OB('OBJ_044', 'Trois marionnettes', 'Accomplir la première fin avec Kankurō.', { type: 'fin', route: 'RTE_01', perso: 'CHR_009' }, ['ALT_005'], 'Kankurō — Trois marionnettes');
  OB('OBJ_045', 'Cœurs de réserve', 'Accomplir la première fin avec Kakuzu.', { type: 'fin', route: 'RTE_01', perso: 'CHR_012' }, ['ALT_006'], 'Kakuzu — Cinq cœurs');
  OB('OBJ_046', 'Lumière', 'Accomplir la branche de la Lumière.', { type: 'fin', route: 'RTE_03' }, ['PSV_144', 'ACT_027'], 'Nature du sage');
  OB('OBJ_047', 'Ombre', 'Accomplir la branche de l’Ombre.', { type: 'fin', route: 'RTE_04' }, ['PSV_140', 'ACT_021'], 'Réincarnation impure');
  OB('OBJ_048', 'Conseil', 'Terminer le Conseil des épreuves.', { type: 'fin', route: 'RTE_05' }, ['DEF_010', 'DEF_011'], 'Défis supplémentaires');
  OB('OBJ_049', 'Brèche', 'Refermer la brèche instable.', { type: 'fin', route: 'RTE_06' }, ['PSV_020'], 'Chute céleste');
  OB('OBJ_050', 'Difficile', 'Accomplir une fin en mode Difficile.', { type: 'fin', difficile: true }, ['DEF_012'], 'Défi : Examen de jōnin');
  OB('OBJ_051', 'Défi : taijutsu', 'Réussir le contrat « Taijutsu pur ».', { type: 'fin', defi: 'DEF_001' }, ['PSV_040', 'PSV_092'], 'Gants de taijutsu, Porte de la Vie');
  OB('OBJ_052', 'Défi : obscurité', 'Réussir le contrat « Nuit sans lune ».', { type: 'fin', defi: 'DEF_002' }, ['PSV_079'], 'Luciole');
  OB('OBJ_053', 'Défi : sans héritage', 'Réussir le contrat « Mains vides ».', { type: 'fin', defi: 'DEF_003' }, ['PSV_109'], 'Parchemin vide');
  OB('OBJ_054', 'Défi : un seul cœur', 'Réussir le contrat « Un souffle ».', { type: 'fin', defi: 'DEF_004' }, ['PSV_096'], 'Substitution instinctive');
  OB('OBJ_055', 'Défi : explosifs', 'Réussir le contrat « Artificier ».', { type: 'fin', defi: 'DEF_005' }, ['PSV_100', 'PSV_102', 'PSV_103'], 'Parchemins spéciaux');
  OB('OBJ_056', 'Défi : clones', 'Réussir le contrat « Mille clones ».', { type: 'fin', defi: 'DEF_006' }, ['PSV_023'], 'Clone de relais');
  OB('OBJ_057', 'Défi : marchand', 'Réussir le contrat « Tout s’achète ».', { type: 'fin', defi: 'DEF_007' }, ['PSV_125'], 'Dés de la grande perdante');
  OB('OBJ_058', 'Défi : pacte', 'Réussir le contrat « Sang pour sang ».', { type: 'fin', defi: 'DEF_008' }, ['PSV_098'], 'Chakra du démon');
  OB('OBJ_059', 'Défi : sable', 'Réussir le contrat « Tempête du désert ».', { type: 'fin', defi: 'DEF_009' }, ['PSV_150'], 'Tempête de sable');
  OB('OBJ_060', 'Défi : conseil', 'Réussir le contrat « Examen de jōnin ».', { type: 'fin', defi: 'DEF_012' }, ['PSV_146'], 'Rasenshuriken');

  // ── Défis (contrats de mission) ──
  const DE = (id, nom, desc, o) => DON.defis.push(Object.assign({ id, nom, desc, statut: 'création originale' }, o));
  DE('DEF_001', 'Taijutsu pur', 'Rock Lee imposé ; aucune salle d’héritage. Atteindre la première fin.', { perso: 'CHR_005', sansHeritage: true, recompenseTexte: 'Gants de taijutsu, Porte de la Vie' });
  DE('DEF_002', 'Nuit sans lune', 'Tous les étages sont plongés dans la pénombre. Première fin.', { obscurite: true, recompenseTexte: 'Luciole' });
  DE('DEF_003', 'Mains vides', 'Aucune salle d’héritage ; les boss donnent tout. Première fin.', { sansHeritage: true, recompenseTexte: 'Parchemin vide' });
  DE('DEF_004', 'Un souffle', 'Un seul contenant, jamais plus ; les contenants deviennent des réserves.', { sante: { vitalite: 1 }, drapeaux: { plafondVit: 1 }, recompenseTexte: 'Substitution instinctive' });
  DE('DEF_005', 'Artificier', 'Départ avec Argile explosive et Argile infinie ; première fin.', { depart: ['PSV_019', 'PSV_110'], recompenseTexte: 'Parchemins spéciaux' });
  DE('DEF_006', 'Mille clones', 'Naruto imposé, départ avec deux Clones de l’ombre et Multi-clonage ; dégâts −30 %.', { perso: 'CHR_001', depart: ['PSV_061', 'PSV_061'], recompenseTexte: 'Clone de relais' });
  DE('DEF_007', 'Tout s’achète', 'Départ avec 50 Ryō et la Carte de membre ; aucune salle d’héritage.', { ressources: { ryo: 50 }, depart: ['PSV_121'], sansHeritage: true, recompenseTexte: 'Dés de la grande perdante' });
  DE('DEF_008', 'Sang pour sang', 'Chaque boss ouvre un pacte ; aucun sanctuaire.', { drapeaux: { serment: true }, recompenseTexte: 'Chakra du démon' });
  DE('DEF_009', 'Tempête du désert', 'Gaara imposé avec Sable en orbite et Sable protecteur ; première fin.', { perso: 'CHR_008', depart: ['PSV_010', 'PSV_065'], recompenseTexte: 'Tempête de sable' });
  DE('DEF_010', 'Course de l’examen', 'Première fin en moins de 20 minutes.', { chrono: 20 * 60, recompenseTexte: 'Marque de vitesse' });
  DE('DEF_011', 'Collectionneur pressé', 'Atteindre l’étage 6 avec au moins 10 objets.', { recompenseTexte: 'Défi' });
  DE('DEF_012', 'Examen de jōnin', 'Mode Difficile imposé, toutes les salles d’épreuve ouvertes.', { difficile: true, recompenseTexte: 'Rasenshuriken' });

  // ── Secrets documentés (indices consultables) ──
  const SE = (id, nom, indice, solution) => DON.secrets.push({ id, nom, indice, solution });
  SE('SEC_001', 'Cache de renseignements', 'Deux salles partagent un mur où rien ne passe…', 'Emplacement voisin d’au moins deux salles ordinaires (souvent trois) ; un explosif contre le mur l’ouvre.');
  SE('SEC_002', 'Chambre isolée', 'Une salle ordinaire, un seul voisin : le vide derrière elle.', 'Case voisine d’exactement une salle de combat et de rien d’autre.');
  SE('SEC_003', 'Rocher à sceau', 'Une spirale claire sur un rocher.', 'Un explosif le brise : réserve, clé, explosifs ou Ryō.');
  SE('SEC_004', 'Statue du pacte', 'Le serpent de pierre du laboratoire regarde vers vous.', 'Un explosif réveille une mue gardienne qui garde un objet de pacte.');
  SE('SEC_005', 'Statue du sanctuaire', 'Le crapaud de pierre semble dormir.', 'Un explosif le réveille ; vaincu, il laisse un fragment de la clé des ermites.');
  SE('SEC_006', 'Clé des ermites', 'Deux fragments font une clé.', 'Deux crapauds gardiens vaincus : la clé ouvre le rayon de la Lumière même après un pacte.');
  SE('SEC_007', 'Autel de tribut', 'Le sang nourrit la pierre, par paliers.', 'Paliers stockés (1 à 12) : Ryō, coffres, réserves, objets du sanctuaire, faveur, puis objet de pacte avec cicatrice.');
  SE('SEC_008', 'Brèche instable', 'Arriver tôt au dernier gardien.', 'Salle du boss de l’étage 8 atteinte en moins de 30:00 : une fissure s’ouvre après la victoire.');
  SE('SEC_009', 'Conseil des épreuves', 'Les juges n’attendent pas les retardataires.', 'Boss de l’étage 6 vaincu en moins de 20:00.');
  SE('SEC_010', 'Pont de débris', 'Un rocher près d’une fosse…', 'Faire exploser un rocher adjacent à une fosse la comble (pont).');
  SE('SEC_011', 'Pakkun le fin limier', 'Les chiens ont du flair.', 'Kakashi et Pakkun signalent un mur secret en entrant dans une salle qui en possède un.');
  SE('SEC_012', 'Refuser un pacte', 'Les ermites observent ceux qui repartent les mains vides.', 'Visiter une salle de pacte sans acheter augmente le poids du sanctuaire (+0,25 par refus).');
  SE('SEC_013', 'Machines fragiles', 'Une loterie n’aime pas les explosions.', 'Un explosif détruit une machine : 2 à 4 Ryō ou demi-cœurs.');
  SE('SEC_014', 'Marchand de pierre', 'La statue de l’échoppe cache sa caisse.', 'Un explosif sur la statue libère 3 à 6 Ryō (une fois).');
  SE('SEC_015', 'Chaînes de la fin', 'Dans les profondeurs, les chaînes cèdent après le combat.', 'Variante « Chambre des chaînes » : les blocs de chaîne s’effacent quand la salle est nettoyée.');
})();
