/**
 * Mise en scène des jutsus : chaque `animationId` des données pointe ici.
 * Une entrée décrit la livraison (corps à corps, projectile, rayon…), les couleurs, l'éclat d'impact
 * et un effet spécial optionnel ; la scène de combat assemble l'animation à partir de ces paramètres.
 */
export interface JutsuAnimation {
  delivery: 'melee' | 'projectile' | 'beam' | 'onTarget' | 'ground' | 'self';
  color: number;
  color2: number;
  /** Nombre de particules à l'impact. */
  burst: number;
  /** Phase de concentration avant le lancer. */
  charge?: boolean;
  size?: number;
  /** Teinte plein écran pendant la technique. */
  screenTint?: number;
  special?: 'blast' | 'dome' | 'flames' | 'lightning' | 'poof' | 'shadow' | 'slashes' | 'spiral' | 'wall' | 'water';
}

export const JUTSU_ANIMATIONS: Record<string, JutsuAnimation> = {
  strike: {
    delivery: 'melee',
    color: 0xffffff,
    color2: 0xf8d070,
    burst: 8,
  },
  multi: {
    delivery: 'melee',
    color: 0xffffff,
    color2: 0xf0a040,
    burst: 6,
  },
  lotus: {
    delivery: 'melee',
    color: 0xf8f0a0,
    color2: 0x58c048,
    burst: 18,
    special: 'spiral',
  },
  palm: {
    delivery: 'melee',
    color: 0x9ad8ff,
    color2: 0xffffff,
    burst: 10,
  },
  palm64: {
    delivery: 'melee',
    color: 0x9ad8ff,
    color2: 0x4ab0ff,
    burst: 14,
    special: 'slashes',
  },
  slash: {
    delivery: 'melee',
    color: 0x8ab0f0,
    color2: 0x4a6ab0,
    burst: 10,
    special: 'slashes',
  },
  throw: {
    delivery: 'projectile',
    color: 0xc0c8d8,
    color2: 0x606878,
    size: 1.5,
    burst: 6,
  },
  fireball: {
    delivery: 'projectile',
    color: 0xf86830,
    color2: 0xf8d048,
    charge: true,
    size: 7,
    burst: 22,
  },
  fireballs: {
    delivery: 'projectile',
    color: 0xf86830,
    color2: 0xf8d048,
    size: 3,
    burst: 8,
  },
  spark: {
    delivery: 'beam',
    color: 0xf8f070,
    color2: 0x70c8ff,
    size: 2,
    burst: 10,
    special: 'lightning',
  },
  lightning: {
    delivery: 'melee',
    color: 0xb8e8ff,
    color2: 0xffffff,
    charge: true,
    burst: 26,
    screenTint: 0x10183a,
    special: 'lightning',
  },
  rasengan: {
    delivery: 'melee',
    color: 0x6ac8ff,
    color2: 0xffffff,
    charge: true,
    burst: 26,
    screenTint: 0x0a1a3a,
    special: 'spiral',
  },
  wind: {
    delivery: 'projectile',
    color: 0xc8f8d0,
    color2: 0x6cc47a,
    size: 4,
    burst: 12,
    special: 'slashes',
  },
  kamatari: {
    delivery: 'onTarget',
    color: 0xc8f8d0,
    color2: 0x6cc47a,
    charge: true,
    burst: 24,
    screenTint: 0x0a2a1a,
    special: 'slashes',
  },
  sand: {
    delivery: 'ground',
    color: 0xd8b070,
    color2: 0xa07840,
    burst: 20,
  },
  quake: {
    delivery: 'ground',
    color: 0xb5834a,
    color2: 0x6a4a2a,
    charge: true,
    burst: 30,
    screenTint: 0x2a1a0a,
  },
  shadow: {
    delivery: 'ground',
    color: 0x100818,
    color2: 0x3a2a4a,
    burst: 8,
    special: 'shadow',
  },
  shark: {
    delivery: 'projectile',
    color: 0x4a8fe8,
    color2: 0xb8e0ff,
    size: 8,
    charge: true,
    burst: 24,
    special: 'water',
  },
  lions: {
    delivery: 'projectile',
    color: 0x6ab8ff,
    color2: 0xe0f4ff,
    size: 7,
    charge: true,
    burst: 24,
    screenTint: 0x0a1a3a,
    special: 'water',
  },
  prison: {
    delivery: 'onTarget',
    color: 0x4a8fe8,
    color2: 0xb8e0ff,
    burst: 16,
    special: 'dome',
  },
  tsukuyomi: {
    delivery: 'onTarget',
    color: 0xd0283a,
    color2: 0x100008,
    charge: true,
    burst: 18,
    screenTint: 0x5a0010,
  },
  amaterasu: {
    delivery: 'onTarget',
    color: 0x100010,
    color2: 0x7a2080,
    charge: true,
    burst: 30,
    screenTint: 0x200010,
    special: 'flames',
  },
  summon: {
    delivery: 'onTarget',
    color: 0xd8d0c0,
    color2: 0x6a5a4a,
    burst: 14,
    special: 'poof',
  },
  heal: {
    delivery: 'self',
    color: 0x78f078,
    color2: 0xe0ffe0,
    burst: 16,
  },
  buff: {
    delivery: 'self',
    color: 0xf8d048,
    color2: 0xffffff,
    burst: 12,
  },
  gates: {
    delivery: 'self',
    color: 0x58f058,
    color2: 0xf8f8a0,
    charge: true,
    burst: 22,
  },
  clone: {
    delivery: 'self',
    color: 0xffffff,
    color2: 0xd0d0d0,
    burst: 16,
    special: 'poof',
  },
  protect: {
    delivery: 'self',
    color: 0xd8b070,
    color2: 0xa07840,
    burst: 12,
    special: 'dome',
  },
  kaiten: {
    delivery: 'self',
    color: 0x9ad8ff,
    color2: 0xffffff,
    burst: 18,
    special: 'dome',
  },
  wall: {
    delivery: 'self',
    color: 0xb5834a,
    color2: 0x6a4a2a,
    burst: 10,
    special: 'wall',
  },
  drain: {
    delivery: 'onTarget',
    color: 0x4a8fe8,
    color2: 0x9a4fd0,
    burst: 14,
  },
  blast: {
    delivery: 'projectile',
    color: 0xf8f8f8,
    color2: 0x9ad8ff,
    size: 4,
    burst: 12,
  },
  expand: {
    delivery: 'self',
    color: 0xf0a860,
    color2: 0xffffff,
    charge: true,
    burst: 18,
  },
  roll: {
    delivery: 'melee',
    color: 0xc8a070,
    color2: 0xf0d8a0,
    burst: 18,
    special: 'spiral',
  },
  pill: {
    delivery: 'self',
    color: 0xf05038,
    color2: 0xf8d048,
    charge: true,
    burst: 20,
  },
  fang: {
    delivery: 'melee',
    color: 0xd8d0c0,
    color2: 0xa08060,
    burst: 16,
    special: 'spiral',
  },
  mind: {
    delivery: 'onTarget',
    color: 0xe87ad0,
    color2: 0xffe0f8,
    charge: true,
    burst: 16,
    screenTint: 0x2a0a2a,
  },
  mindlink: {
    delivery: 'self',
    color: 0xe87ad0,
    color2: 0x9ad8ff,
    burst: 16,
  },
  puppet: {
    delivery: 'self',
    color: 0x7a3ab8,
    color2: 0xd8cfc0,
    burst: 14,
    special: 'poof',
  },
  needles: {
    delivery: 'projectile',
    color: 0xd8e8f8,
    color2: 0x7aa8d8,
    size: 1.5,
    burst: 10,
    special: 'slashes',
  },
  puppet_trap: {
    delivery: 'onTarget',
    color: 0x2a2a38,
    color2: 0x9a4fd0,
    charge: true,
    burst: 20,
    screenTint: 0x1a0a2a,
    special: 'dome',
  },
  mirrors: {
    delivery: 'onTarget',
    color: 0xd8f4ff,
    color2: 0x7ac8f0,
    charge: true,
    burst: 26,
    screenTint: 0x0a1a2a,
    special: 'slashes',
  },
  mist: {
    delivery: 'self',
    color: 0xd8e0e8,
    color2: 0x8a9aa8,
    burst: 22,
    special: 'poof',
  },
  water_dragon: {
    delivery: 'projectile',
    color: 0x3a7ae8,
    color2: 0xc8e8ff,
    size: 9,
    charge: true,
    burst: 28,
    screenTint: 0x0a1a3a,
    special: 'water',
  },
  clay: {
    delivery: 'projectile',
    color: 0xf0ece0,
    color2: 0xc8b898,
    size: 2,
    burst: 10,
    special: 'blast',
  },
  clay_bird: {
    delivery: 'projectile',
    color: 0xf0ece0,
    color2: 0xf8a030,
    size: 5,
    burst: 18,
    special: 'blast',
  },
  explosion: {
    delivery: 'onTarget',
    color: 0xf8a030,
    color2: 0xfff0a0,
    charge: true,
    burst: 34,
    screenTint: 0x3a1a00,
    special: 'blast',
  },
  needle_guard: {
    delivery: 'self',
    color: 0xeeeae0,
    color2: 0xa8a090,
    burst: 14,
    special: 'dome',
  },
  oil_flame: {
    delivery: 'projectile',
    color: 0xf86830,
    color2: 0x7a5a20,
    size: 8,
    charge: true,
    burst: 26,
    screenTint: 0x2a0a00,
    special: 'flames',
  },
  summon_toad: {
    delivery: 'onTarget',
    color: 0xc84a3a,
    color2: 0xf0d8a0,
    charge: true,
    burst: 24,
    screenTint: 0x1a0a0a,
    special: 'poof',
  },
};

export function animationFor(id: string): JutsuAnimation {
  return JUTSU_ANIMATIONS[id] ?? JUTSU_ANIMATIONS.blast;
}
